/*
  PSM-Smart Oracle 21c schema script.

  Scope:
  - Drop old schema objects for repeatable local initialization.
  - Create database framework: tables, constraints, comments, sequences, indexes.

  This script intentionally does not insert business data.
*/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAINT_TASK CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ALARM_LOG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TS_RAW_DATA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TAG_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEVICE_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BAY_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SYS_USER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAINT_PERSON CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STATION_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAINT_TASK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALARM_LOG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TS_RAW_DATA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TAG_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEVICE_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BAY_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SYS_USER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAINT_PERSON';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STATION_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE STATION_BASE (
  ID NUMBER(19) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  VOLTAGE_LEVEL VARCHAR2(20),
  LOCATION VARCHAR2(200),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STATION_BASE PRIMARY KEY (ID),
  CONSTRAINT UK_STATION_BASE_NAME UNIQUE (NAME)
);

CREATE TABLE BAY_BASE (
  ID NUMBER(19) NOT NULL,
  STATION_ID NUMBER(19) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  BAY_TYPE VARCHAR2(50),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_BAY_BASE PRIMARY KEY (ID),
  CONSTRAINT FK_BAY_STATION FOREIGN KEY (STATION_ID) REFERENCES STATION_BASE (ID),
  CONSTRAINT UK_BAY_STATION_NAME UNIQUE (STATION_ID, NAME)
);

CREATE TABLE DEVICE_BASE (
  ID NUMBER(19) NOT NULL,
  BAY_ID NUMBER(19) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DEVICE_TYPE VARCHAR2(50) NOT NULL,
  CURRENT_LIMIT NUMBER(12, 3),
  TEMP_LIMIT NUMBER(12, 3),
  TEMP_RATE_LIMIT NUMBER(12, 3),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DEVICE_BASE PRIMARY KEY (ID),
  CONSTRAINT FK_DEVICE_BAY FOREIGN KEY (BAY_ID) REFERENCES BAY_BASE (ID),
  CONSTRAINT UK_DEVICE_BAY_NAME UNIQUE (BAY_ID, NAME),
  CONSTRAINT CK_DEVICE_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE TABLE TAG_BASE (
  ID NUMBER(19) NOT NULL,
  DEVICE_ID NUMBER(19) NOT NULL,
  TAG_CODE VARCHAR2(64) NOT NULL,
  TAG_NAME VARCHAR2(100) NOT NULL,
  UNIT VARCHAR2(20),
  WARN_LIMIT NUMBER(12, 3),
  RATE_LIMIT NUMBER(12, 3),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TAG_BASE PRIMARY KEY (ID),
  CONSTRAINT FK_TAG_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_BASE (ID),
  CONSTRAINT UK_TAG_DEVICE_CODE UNIQUE (DEVICE_ID, TAG_CODE)
);

CREATE TABLE TS_RAW_DATA (
  ID NUMBER(19) NOT NULL,
  DEVICE_ID NUMBER(19) NOT NULL,
  TAG_ID NUMBER(19),
  SAMPLE_TIME TIMESTAMP NOT NULL,
  VAL NUMBER(14, 4) NOT NULL,
  FREQ_FLAG NUMBER(1) NOT NULL,
  QUALITY_FLAG NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TS_RAW_DATA PRIMARY KEY (ID),
  CONSTRAINT FK_TS_RAW_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_BASE (ID),
  CONSTRAINT FK_TS_RAW_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG_BASE (ID),
  CONSTRAINT CK_TS_RAW_FREQ_FLAG CHECK (FREQ_FLAG IN (0, 1)),
  CONSTRAINT CK_TS_RAW_QUALITY CHECK (QUALITY_FLAG IN (0, 1, 2))
);

CREATE TABLE ALARM_LOG (
  ID NUMBER(19) NOT NULL,
  DEVICE_ID NUMBER(19) NOT NULL,
  TAG_ID NUMBER(19),
  ALARM_TYPE VARCHAR2(50) NOT NULL,
  ALARM_LEVEL VARCHAR2(20) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP,
  START_VAL NUMBER(14, 4),
  END_VAL NUMBER(14, 4),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ALARM_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_ALARM_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_BASE (ID),
  CONSTRAINT FK_ALARM_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG_BASE (ID),
  CONSTRAINT CK_ALARM_LEVEL CHECK (ALARM_LEVEL IN ('WARN', 'SERIOUS')),
  CONSTRAINT CK_ALARM_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE MAINT_TASK (
  TASK_ID NUMBER(19) NOT NULL,
  ALARM_ID NUMBER(19) NOT NULL,
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  ASSIGNEE VARCHAR2(100),
  FEEDBACK VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  FINISHED_AT TIMESTAMP,
  CONSTRAINT PK_MAINT_TASK PRIMARY KEY (TASK_ID),
  CONSTRAINT FK_TASK_ALARM FOREIGN KEY (ALARM_ID) REFERENCES ALARM_LOG (ID),
  CONSTRAINT CK_MAINT_TASK_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE TABLE MAINT_PERSON (
  ID NUMBER(19) NOT NULL,
  PERSON_NAME VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(30),
  EMAIL VARCHAR2(100),
  DEPARTMENT VARCHAR2(100),
  SPECIALTY VARCHAR2(100),
  CERT_NO VARCHAR2(100),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_MAINT_PERSON PRIMARY KEY (ID),
  CONSTRAINT UK_MAINT_PERSON_PHONE UNIQUE (PHONE),
  CONSTRAINT CK_MAINT_PERSON_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE SYS_USER (
  ID NUMBER(19) NOT NULL,
  USERNAME VARCHAR2(64) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  DISPLAY_NAME VARCHAR2(100) NOT NULL,
  ROLE_CODE VARCHAR2(50) NOT NULL,
  PERSON_ID NUMBER(19),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  LAST_LOGIN_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_SYS_USER PRIMARY KEY (ID),
  CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT FK_SYS_USER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES MAINT_PERSON (ID),
  CONSTRAINT CK_SYS_USER_ROLE CHECK (ROLE_CODE IN ('ADMIN', 'OPERATOR', 'ENGINEER', 'MANAGER')),
  CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN (0, 1))
);

COMMENT ON TABLE STATION_BASE IS '变电站基础台账表，记录变电站名称、电压等级和地理位置等基础信息';
COMMENT ON COLUMN STATION_BASE.ID IS '变电站主键 ID，使用 SEQ_STATION_BASE 生成';
COMMENT ON COLUMN STATION_BASE.NAME IS '变电站名称，例如城东 110kV 变电站';
COMMENT ON COLUMN STATION_BASE.VOLTAGE_LEVEL IS '电压等级，例如 110kV、220kV';
COMMENT ON COLUMN STATION_BASE.LOCATION IS '变电站位置或地址描述';
COMMENT ON COLUMN STATION_BASE.CREATED_AT IS '记录创建时间';

COMMENT ON TABLE BAY_BASE IS '间隔台账表，表示变电站下的主变间隔、出线间隔等一次设备间隔';
COMMENT ON COLUMN BAY_BASE.ID IS '间隔主键 ID，使用 SEQ_BAY_BASE 生成';
COMMENT ON COLUMN BAY_BASE.STATION_ID IS '所属变电站 ID，关联 STATION_BASE.ID';
COMMENT ON COLUMN BAY_BASE.NAME IS '间隔名称，例如 1号主变间隔、10kV 出线间隔';
COMMENT ON COLUMN BAY_BASE.BAY_TYPE IS '间隔类型，例如 TRANSFORMER 表示主变间隔，FEEDER 表示出线间隔';
COMMENT ON COLUMN BAY_BASE.CREATED_AT IS '记录创建时间';

COMMENT ON TABLE DEVICE_BASE IS '设备台账表，记录变压器、母线等被监测设备及其告警阈值';
COMMENT ON COLUMN DEVICE_BASE.ID IS '设备主键 ID，使用 SEQ_DEVICE_BASE 生成';
COMMENT ON COLUMN DEVICE_BASE.BAY_ID IS '所属间隔 ID，关联 BAY_BASE.ID';
COMMENT ON COLUMN DEVICE_BASE.NAME IS '设备名称，例如 1号主变压器、10kV I段母线';
COMMENT ON COLUMN DEVICE_BASE.DEVICE_TYPE IS '设备类型，例如 TRANSFORMER、BUS';
COMMENT ON COLUMN DEVICE_BASE.CURRENT_LIMIT IS '设备电流越限阈值，单位由具体测点定义';
COMMENT ON COLUMN DEVICE_BASE.TEMP_LIMIT IS '设备温度越限阈值，单位通常为摄氏度';
COMMENT ON COLUMN DEVICE_BASE.TEMP_RATE_LIMIT IS '设备温升变化率阈值，用于触发动态高频采样';
COMMENT ON COLUMN DEVICE_BASE.STATUS IS '设备状态：0 正常，1 告警，2 停运或不可用';
COMMENT ON COLUMN DEVICE_BASE.CREATED_AT IS '记录创建时间';

COMMENT ON TABLE TAG_BASE IS '测点台账表，记录设备下的电流、温度、电压等监测点';
COMMENT ON COLUMN TAG_BASE.ID IS '测点主键 ID，使用 SEQ_TAG_BASE 生成';
COMMENT ON COLUMN TAG_BASE.DEVICE_ID IS '所属设备 ID，关联 DEVICE_BASE.ID';
COMMENT ON COLUMN TAG_BASE.TAG_CODE IS '测点编码，设备内唯一，用于接口和采集程序识别';
COMMENT ON COLUMN TAG_BASE.TAG_NAME IS '测点名称，例如负荷电流、油温、绕组温度';
COMMENT ON COLUMN TAG_BASE.UNIT IS '测点单位，例如 A、C、kV';
COMMENT ON COLUMN TAG_BASE.WARN_LIMIT IS '测点越限预警阈值';
COMMENT ON COLUMN TAG_BASE.RATE_LIMIT IS '测点变化率预警阈值';
COMMENT ON COLUMN TAG_BASE.CREATED_AT IS '记录创建时间';

COMMENT ON TABLE TS_RAW_DATA IS '实时采样数据表，保存分钟级常规采样和秒级高频录波数据';
COMMENT ON COLUMN TS_RAW_DATA.ID IS '采样数据主键 ID，使用 SEQ_TS_RAW_DATA 生成';
COMMENT ON COLUMN TS_RAW_DATA.DEVICE_ID IS '采样所属设备 ID，关联 DEVICE_BASE.ID';
COMMENT ON COLUMN TS_RAW_DATA.TAG_ID IS '采样所属测点 ID，关联 TAG_BASE.ID';
COMMENT ON COLUMN TS_RAW_DATA.SAMPLE_TIME IS '采样时间，秒级高频数据使用 TIMESTAMP 精度';
COMMENT ON COLUMN TS_RAW_DATA.VAL IS '采样值';
COMMENT ON COLUMN TS_RAW_DATA.FREQ_FLAG IS '采样频率标记：0 表示 1 分钟常规采样，1 表示 1 秒高频采样';
COMMENT ON COLUMN TS_RAW_DATA.QUALITY_FLAG IS '数据质量标记：0 正常，1 可疑，2 无效';
COMMENT ON COLUMN TS_RAW_DATA.CREATED_AT IS '数据入库时间';

COMMENT ON TABLE ALARM_LOG IS '告警记录表，保存越限、变化率异常等事件及其处理状态';
COMMENT ON COLUMN ALARM_LOG.ID IS '告警主键 ID，使用 SEQ_ALARM_LOG 生成';
COMMENT ON COLUMN ALARM_LOG.DEVICE_ID IS '告警所属设备 ID，关联 DEVICE_BASE.ID';
COMMENT ON COLUMN ALARM_LOG.TAG_ID IS '告警所属测点 ID，关联 TAG_BASE.ID';
COMMENT ON COLUMN ALARM_LOG.ALARM_TYPE IS '告警类型，例如 TEMP_RATE 表示温升变化率异常';
COMMENT ON COLUMN ALARM_LOG.ALARM_LEVEL IS '告警级别：WARN 预警，SERIOUS 严重告警';
COMMENT ON COLUMN ALARM_LOG.START_TIME IS '告警开始时间';
COMMENT ON COLUMN ALARM_LOG.END_TIME IS '告警结束时间，未恢复时为空';
COMMENT ON COLUMN ALARM_LOG.START_VAL IS '告警触发时的起始参考值';
COMMENT ON COLUMN ALARM_LOG.END_VAL IS '告警结束或峰值参考值';
COMMENT ON COLUMN ALARM_LOG.STATUS IS '告警状态：0 活跃，1 已关闭';
COMMENT ON COLUMN ALARM_LOG.CREATED_AT IS '记录创建时间';

COMMENT ON TABLE MAINT_TASK IS '维保工单表，严重告警触发后自动生成并跟踪处理闭环';
COMMENT ON COLUMN MAINT_TASK.TASK_ID IS '工单主键 ID，使用 SEQ_MAINT_TASK 生成';
COMMENT ON COLUMN MAINT_TASK.ALARM_ID IS '关联告警 ID，关联 ALARM_LOG.ID';
COMMENT ON COLUMN MAINT_TASK.STATUS IS '工单状态：0 待办，1 处理中，2 已完成';
COMMENT ON COLUMN MAINT_TASK.ASSIGNEE IS '工单处理人或当前负责人';
COMMENT ON COLUMN MAINT_TASK.FEEDBACK IS '工程师处理反馈';
COMMENT ON COLUMN MAINT_TASK.CREATED_AT IS '工单创建时间';
COMMENT ON COLUMN MAINT_TASK.UPDATED_AT IS '工单最近更新时间';
COMMENT ON COLUMN MAINT_TASK.FINISHED_AT IS '工单完成时间';

COMMENT ON TABLE MAINT_PERSON IS '维保人员个人信息表，保存工程师联系信息、专业方向和在岗状态';
COMMENT ON COLUMN MAINT_PERSON.ID IS '维保人员主键 ID，使用 SEQ_MAINT_PERSON 生成';
COMMENT ON COLUMN MAINT_PERSON.PERSON_NAME IS '维保人员姓名';
COMMENT ON COLUMN MAINT_PERSON.PHONE IS '联系电话，表内唯一';
COMMENT ON COLUMN MAINT_PERSON.EMAIL IS '电子邮箱';
COMMENT ON COLUMN MAINT_PERSON.DEPARTMENT IS '所属部门或班组';
COMMENT ON COLUMN MAINT_PERSON.SPECIALTY IS '专业方向，例如变压器检修、继电保护';
COMMENT ON COLUMN MAINT_PERSON.CERT_NO IS '资质证书编号或上岗证编号';
COMMENT ON COLUMN MAINT_PERSON.STATUS IS '人员状态：0 在岗，1 停用或离岗';
COMMENT ON COLUMN MAINT_PERSON.CREATED_AT IS '记录创建时间';
COMMENT ON COLUMN MAINT_PERSON.UPDATED_AT IS '记录最近更新时间';

COMMENT ON TABLE SYS_USER IS '系统用户账号表，用于前端登录、角色识别和账号状态控制';
COMMENT ON COLUMN SYS_USER.ID IS '系统用户主键 ID，使用 SEQ_SYS_USER 生成';
COMMENT ON COLUMN SYS_USER.USERNAME IS '登录用户名，表内唯一';
COMMENT ON COLUMN SYS_USER.PASSWORD_HASH IS '密码哈希值，禁止存储明文密码';
COMMENT ON COLUMN SYS_USER.DISPLAY_NAME IS '前端展示名称';
COMMENT ON COLUMN SYS_USER.ROLE_CODE IS '角色编码：ADMIN 管理员，OPERATOR 运行监控，ENGINEER 维保工程师，MANAGER 管理人员';
COMMENT ON COLUMN SYS_USER.PERSON_ID IS '关联维保人员 ID，工程师账号可绑定 MAINT_PERSON.ID';
COMMENT ON COLUMN SYS_USER.STATUS IS '账号状态：0 启用，1 禁用';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_AT IS '最近登录时间';
COMMENT ON COLUMN SYS_USER.CREATED_AT IS '账号创建时间';
COMMENT ON COLUMN SYS_USER.UPDATED_AT IS '账号最近更新时间';

CREATE SEQUENCE SEQ_STATION_BASE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BAY_BASE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEVICE_BASE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TAG_BASE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TS_RAW_DATA START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE SEQ_ALARM_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAINT_TASK START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAINT_PERSON START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_TS_RAW_DEVICE_TIME ON TS_RAW_DATA (DEVICE_ID, SAMPLE_TIME);
CREATE INDEX IDX_TS_RAW_TAG_TIME ON TS_RAW_DATA (TAG_ID, SAMPLE_TIME);
CREATE INDEX IDX_ALARM_DEVICE_TIME ON ALARM_LOG (DEVICE_ID, START_TIME);
CREATE INDEX IDX_TASK_ALARM ON MAINT_TASK (ALARM_ID);
CREATE INDEX IDX_SYS_USER_PERSON ON SYS_USER (PERSON_ID);
