/*
  PSM-Smart Oracle 21c asset management extension.

  Adds soft-delete columns, active-only uniqueness, asset maintenance package,
  and status linkage triggers for alarms/tasks.
*/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PSM_ALARM_OPEN_STATUS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PSM_TASK_COMPLETE_STATUS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_ASSET';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_BACKUP';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'BOX_TRANSFORMER'
    AND COLUMN_NAME = 'IS_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BOX_TRANSFORMER ADD (IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'POWER_CIRCUIT'
    AND COLUMN_NAME = 'IS_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE POWER_CIRCUIT ADD (IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'MEASURE_POINT'
    AND COLUMN_NAME = 'IS_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MEASURE_POINT ADD (IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

UPDATE BOX_TRANSFORMER SET IS_DELETED = 0 WHERE IS_DELETED IS NULL;
UPDATE POWER_CIRCUIT SET IS_DELETED = 0 WHERE IS_DELETED IS NULL;
UPDATE MEASURE_POINT SET IS_DELETED = 0 WHERE IS_DELETED IS NULL;

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_BOX_TRANSFORMER_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BOX_TRANSFORMER ADD CONSTRAINT CK_BOX_TRANSFORMER_DELETED CHECK (IS_DELETED IN (0, 1))';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_POWER_CIRCUIT_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE POWER_CIRCUIT ADD CONSTRAINT CK_POWER_CIRCUIT_DELETED CHECK (IS_DELETED IN (0, 1))';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_MEASURE_POINT_DELETED';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MEASURE_POINT ADD CONSTRAINT CK_MEASURE_POINT_DELETED CHECK (IS_DELETED IN (0, 1))';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BOX_TRANSFORMER DROP CONSTRAINT UK_BOX_TRANSFORMER_CODE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BOX_TRANSFORMER DROP CONSTRAINT UK_BOX_TRANSFORMER_NAME';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE POWER_CIRCUIT DROP CONSTRAINT UK_CIRCUIT_TRANSFORMER_CODE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE MEASURE_POINT DROP CONSTRAINT UK_POINT_TRANSFORMER_CODE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UK_BOX_TRANSFORMER_CODE_ACTIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UK_BOX_TRANSFORMER_NAME_ACTIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UK_CIRCUIT_CODE_ACTIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX UK_POINT_CODE_ACTIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

CREATE UNIQUE INDEX UK_BOX_TRANSFORMER_CODE_ACTIVE
  ON BOX_TRANSFORMER (
    CASE WHEN IS_DELETED = 0 THEN UPPER(TRIM(TRANSFORMER_CODE)) END
  );

CREATE UNIQUE INDEX UK_BOX_TRANSFORMER_NAME_ACTIVE
  ON BOX_TRANSFORMER (
    CASE WHEN IS_DELETED = 0 THEN UPPER(TRIM(NAME)) END
  );

CREATE UNIQUE INDEX UK_CIRCUIT_CODE_ACTIVE
  ON POWER_CIRCUIT (
    CASE WHEN IS_DELETED = 0 THEN TRANSFORMER_ID END,
    CASE WHEN IS_DELETED = 0 THEN UPPER(TRIM(CIRCUIT_CODE)) END
  );

CREATE UNIQUE INDEX UK_POINT_CODE_ACTIVE
  ON MEASURE_POINT (
    CASE WHEN IS_DELETED = 0 THEN TRANSFORMER_ID END,
    CASE WHEN IS_DELETED = 0 THEN UPPER(TRIM(POINT_CODE)) END
  );

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_DATA_SNAPSHOT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DATA_SNAPSHOT START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT (
        ID NUMBER(19) NOT NULL,
        SNAPSHOT_NAME VARCHAR2(100) NOT NULL,
        NOTE VARCHAR2(500),
        TRANSFORMER_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        CIRCUIT_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        POINT_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        RAW_DATA_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        ARCHIVE_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        DOOR_LOG_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        ALARM_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        TASK_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        CREATED_BY VARCHAR2(64),
        CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
        RESTORED_BY VARCHAR2(64),
        RESTORED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT PRIMARY KEY (ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_TRANSFORMER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_TRANSFORMER (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_CODE VARCHAR2(64) NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        TRANSFORMER_TYPE VARCHAR2(50) NOT NULL,
        RATED_CAPACITY_KVA NUMBER(12, 3),
        RATED_VOLTAGE_RATIO VARCHAR2(50),
        COMMISSION_DATE DATE,
        MANUFACTURER VARCHAR2(100),
        OIL_LEVEL NUMBER(12, 3),
        LOCATION VARCHAR2(200),
        STATUS NUMBER(2) NOT NULL,
        IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_TRANSFORMER PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_CIRCUIT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_CIRCUIT (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        CIRCUIT_CODE VARCHAR2(64) NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        DIRECTION VARCHAR2(20) NOT NULL,
        RATED_VOLTAGE_KV NUMBER(12, 3),
        RATED_CURRENT_A NUMBER(12, 3),
        STATUS NUMBER(2) NOT NULL,
        IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_CIRCUIT PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_POINT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_POINT (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        CIRCUIT_ID NUMBER(19),
        POINT_CODE VARCHAR2(64) NOT NULL,
        POINT_NAME VARCHAR2(100) NOT NULL,
        POINT_GROUP VARCHAR2(50) NOT NULL,
        MEASURE_TYPE VARCHAR2(50) NOT NULL,
        PHASE_CODE VARCHAR2(20) NOT NULL,
        UNIT VARCHAR2(20),
        MIN_LIMIT NUMBER(14, 4),
        MAX_LIMIT NUMBER(14, 4),
        RATE_LIMIT NUMBER(14, 4),
        STATUS NUMBER(2) NOT NULL,
        IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_POINT PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_RAW_DATA';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_RAW_DATA (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        CIRCUIT_ID NUMBER(19),
        POINT_ID NUMBER(19) NOT NULL,
        SAMPLE_TIME TIMESTAMP NOT NULL,
        VAL NUMBER(14, 4) NOT NULL,
        QUALITY_FLAG NUMBER(2) NOT NULL,
        CREATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_RAW_DATA PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_DAY_ARCHIVE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_DAY_ARCHIVE (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        ARCHIVE_DAY DATE NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        CIRCUIT_ID NUMBER(19),
        POINT_ID NUMBER(19) NOT NULL,
        DISPLAY_VAL NUMBER(14, 4) NOT NULL,
        AVG_VAL NUMBER(14, 4),
        MIN_VAL NUMBER(14, 4),
        MAX_VAL NUMBER(14, 4),
        SAMPLE_COUNT NUMBER(19) NOT NULL,
        MAX_QUALITY_FLAG NUMBER(2) NOT NULL,
        CREATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_DAY_ARCHIVE PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_DOOR_LOG';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_DOOR_LOG (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        POINT_ID NUMBER(19),
        EVENT_TYPE VARCHAR2(30) NOT NULL,
        EVENT_TIME TIMESTAMP NOT NULL,
        DOOR_STATUS NUMBER(1) NOT NULL,
        NOTE VARCHAR2(500),
        CREATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_DOOR_LOG PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_ALARM';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_ALARM (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        ID NUMBER(19) NOT NULL,
        TRANSFORMER_ID NUMBER(19) NOT NULL,
        CIRCUIT_ID NUMBER(19),
        POINT_ID NUMBER(19),
        ALARM_TYPE VARCHAR2(50) NOT NULL,
        ALARM_LEVEL VARCHAR2(20) NOT NULL,
        START_TIME TIMESTAMP NOT NULL,
        END_TIME TIMESTAMP,
        START_VAL NUMBER(14, 4),
        END_VAL NUMBER(14, 4),
        STATUS NUMBER(2) NOT NULL,
        CREATED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_ALARM PRIMARY KEY (SNAPSHOT_ID, ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT_TASK';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT_TASK (
        SNAPSHOT_ID NUMBER(19) NOT NULL,
        TASK_ID NUMBER(19) NOT NULL,
        ALARM_ID NUMBER(19) NOT NULL,
        STATUS NUMBER(2) NOT NULL,
        ASSIGNEE VARCHAR2(100),
        FEEDBACK VARCHAR2(1000),
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        FINISHED_AT TIMESTAMP,
        CONSTRAINT PK_DATA_SNAPSHOT_TASK PRIMARY KEY (SNAPSHOT_ID, TASK_ID)
      )
    ]';
  END IF;
END;
/

CREATE OR REPLACE PACKAGE PKG_PSM_BACKUP AS
  PROCEDURE CREATE_SNAPSHOT(
      P_SNAPSHOT_NAME IN VARCHAR2,
      P_NOTE          IN VARCHAR2,
      P_ACTOR         IN VARCHAR2,
      P_SNAPSHOT_ID   OUT NUMBER
  );

  PROCEDURE RESTORE_SNAPSHOT(
      P_SNAPSHOT_ID IN NUMBER,
      P_ACTOR       IN VARCHAR2
  );
END PKG_PSM_BACKUP;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_BACKUP AS
  FUNCTION NORMALIZE_TEXT(P_TEXT IN VARCHAR2, P_LIMIT IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN SUBSTR(NULLIF(TRIM(P_TEXT), ''), 1, P_LIMIT);
  END NORMALIZE_TEXT;

  PROCEDURE ASSERT_SNAPSHOT(P_SNAPSHOT_ID IN NUMBER) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM DATA_SNAPSHOT
    WHERE ID = P_SNAPSHOT_ID;

    IF V_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20600, 'Snapshot does not exist.');
    END IF;
  END ASSERT_SNAPSHOT;

  PROCEDURE BUMP_SEQUENCE(P_SEQUENCE_NAME IN VARCHAR2, P_MIN_NEXT_VALUE IN NUMBER) IS
    V_CURRENT_VALUE NUMBER;
    V_INCREMENT NUMBER;
  BEGIN
    IF P_MIN_NEXT_VALUE IS NULL OR P_MIN_NEXT_VALUE <= 1 THEN
      RETURN;
    END IF;

    EXECUTE IMMEDIATE 'SELECT ' || P_SEQUENCE_NAME || '.NEXTVAL FROM DUAL' INTO V_CURRENT_VALUE;
    IF V_CURRENT_VALUE < P_MIN_NEXT_VALUE THEN
      V_INCREMENT := P_MIN_NEXT_VALUE - V_CURRENT_VALUE;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY ' || V_INCREMENT;
      EXECUTE IMMEDIATE 'SELECT ' || P_SEQUENCE_NAME || '.NEXTVAL FROM DUAL' INTO V_CURRENT_VALUE;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY 1';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY 1';
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
      RAISE;
  END BUMP_SEQUENCE;

  PROCEDURE BUMP_ALL_SEQUENCES IS
    V_MIN_NEXT_VALUE NUMBER;
  BEGIN
    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM BOX_TRANSFORMER;
    BUMP_SEQUENCE('SEQ_BOX_TRANSFORMER', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM POWER_CIRCUIT;
    BUMP_SEQUENCE('SEQ_POWER_CIRCUIT', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM MEASURE_POINT;
    BUMP_SEQUENCE('SEQ_MEASURE_POINT', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM TS_RAW_DATA;
    BUMP_SEQUENCE('SEQ_TS_RAW_DATA', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM TS_RAW_DATA_DAY_ARCHIVE;
    BUMP_SEQUENCE('SEQ_TS_RAW_DATA_DAY_ARCHIVE', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM CABINET_DOOR_LOG;
    BUMP_SEQUENCE('SEQ_CABINET_DOOR_LOG', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM ALARM_LOG;
    BUMP_SEQUENCE('SEQ_ALARM_LOG', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(TASK_ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM MAINT_TASK;
    BUMP_SEQUENCE('SEQ_MAINT_TASK', V_MIN_NEXT_VALUE);
  END BUMP_ALL_SEQUENCES;

  PROCEDURE CREATE_SNAPSHOT(
      P_SNAPSHOT_NAME IN VARCHAR2,
      P_NOTE          IN VARCHAR2,
      P_ACTOR         IN VARCHAR2,
      P_SNAPSHOT_ID   OUT NUMBER
  ) IS
    V_NAME VARCHAR2(100) := NVL(NORMALIZE_TEXT(P_SNAPSHOT_NAME, 100), 'snapshot-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));
    V_NOTE VARCHAR2(500) := NORMALIZE_TEXT(P_NOTE, 500);
    V_ACTOR VARCHAR2(64) := NORMALIZE_TEXT(P_ACTOR, 64);
    V_TRANSFORMER_COUNT NUMBER := 0;
    V_CIRCUIT_COUNT NUMBER := 0;
    V_POINT_COUNT NUMBER := 0;
    V_RAW_DATA_COUNT NUMBER := 0;
    V_ARCHIVE_COUNT NUMBER := 0;
    V_DOOR_LOG_COUNT NUMBER := 0;
    V_ALARM_COUNT NUMBER := 0;
    V_TASK_COUNT NUMBER := 0;
  BEGIN
    P_SNAPSHOT_ID := SEQ_DATA_SNAPSHOT.NEXTVAL;

    INSERT INTO DATA_SNAPSHOT (
      ID,
      SNAPSHOT_NAME,
      NOTE,
      CREATED_BY,
      CREATED_AT
    ) VALUES (
      P_SNAPSHOT_ID,
      V_NAME,
      V_NOTE,
      V_ACTOR,
      LOCALTIMESTAMP
    );

    INSERT INTO DATA_SNAPSHOT_TRANSFORMER (
      SNAPSHOT_ID, ID, TRANSFORMER_CODE, NAME, TRANSFORMER_TYPE,
      RATED_CAPACITY_KVA, RATED_VOLTAGE_RATIO, COMMISSION_DATE, MANUFACTURER,
      OIL_LEVEL, LOCATION, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_CODE, NAME, TRANSFORMER_TYPE,
      RATED_CAPACITY_KVA, RATED_VOLTAGE_RATIO, COMMISSION_DATE, MANUFACTURER,
      OIL_LEVEL, LOCATION, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM BOX_TRANSFORMER;
    V_TRANSFORMER_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_CIRCUIT (
      SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION,
      RATED_VOLTAGE_KV, RATED_CURRENT_A, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION,
      RATED_VOLTAGE_KV, RATED_CURRENT_A, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM POWER_CIRCUIT;
    V_CIRCUIT_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_POINT (
      SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME,
      POINT_GROUP, MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT,
      RATE_LIMIT, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME,
      POINT_GROUP, MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT,
      RATE_LIMIT, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM MEASURE_POINT;
    V_POINT_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_RAW_DATA (
      SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME,
      VAL, QUALITY_FLAG, CREATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME,
      VAL, QUALITY_FLAG, CREATED_AT
    FROM TS_RAW_DATA;
    V_RAW_DATA_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_DAY_ARCHIVE (
      SNAPSHOT_ID, ID, ARCHIVE_DAY, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID,
      DISPLAY_VAL, AVG_VAL, MIN_VAL, MAX_VAL, SAMPLE_COUNT, MAX_QUALITY_FLAG,
      CREATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, ARCHIVE_DAY, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID,
      DISPLAY_VAL, AVG_VAL, MIN_VAL, MAX_VAL, SAMPLE_COUNT, MAX_QUALITY_FLAG,
      CREATED_AT
    FROM TS_RAW_DATA_DAY_ARCHIVE;
    V_ARCHIVE_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_DOOR_LOG (
      SNAPSHOT_ID, ID, TRANSFORMER_ID, POINT_ID, EVENT_TYPE, EVENT_TIME,
      DOOR_STATUS, NOTE, CREATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_ID, POINT_ID, EVENT_TYPE, EVENT_TIME,
      DOOR_STATUS, NOTE, CREATED_AT
    FROM CABINET_DOOR_LOG;
    V_DOOR_LOG_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_ALARM (
      SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, ALARM_TYPE,
      ALARM_LEVEL, START_TIME, END_TIME, START_VAL, END_VAL, STATUS, CREATED_AT
    )
    SELECT
      P_SNAPSHOT_ID, ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, ALARM_TYPE,
      ALARM_LEVEL, START_TIME, END_TIME, START_VAL, END_VAL, STATUS, CREATED_AT
    FROM ALARM_LOG;
    V_ALARM_COUNT := SQL%ROWCOUNT;

    INSERT INTO DATA_SNAPSHOT_TASK (
      SNAPSHOT_ID, TASK_ID, ALARM_ID, STATUS, ASSIGNEE, FEEDBACK,
      CREATED_AT, UPDATED_AT, FINISHED_AT
    )
    SELECT
      P_SNAPSHOT_ID, TASK_ID, ALARM_ID, STATUS, ASSIGNEE, FEEDBACK,
      CREATED_AT, UPDATED_AT, FINISHED_AT
    FROM MAINT_TASK;
    V_TASK_COUNT := SQL%ROWCOUNT;

    UPDATE DATA_SNAPSHOT
    SET
      TRANSFORMER_COUNT = V_TRANSFORMER_COUNT,
      CIRCUIT_COUNT = V_CIRCUIT_COUNT,
      POINT_COUNT = V_POINT_COUNT,
      RAW_DATA_COUNT = V_RAW_DATA_COUNT,
      ARCHIVE_COUNT = V_ARCHIVE_COUNT,
      DOOR_LOG_COUNT = V_DOOR_LOG_COUNT,
      ALARM_COUNT = V_ALARM_COUNT,
      TASK_COUNT = V_TASK_COUNT
    WHERE ID = P_SNAPSHOT_ID;

    COMMIT;
    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'BACKUP_CREATE',
      'Created data snapshot ' || P_SNAPSHOT_ID,
      'actor=' || NVL(V_ACTOR, 'unknown') || ' rawRows=' || V_RAW_DATA_COUNT
    );
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PKG_PSM_LOG.WRITE_LOG('ERROR', 'BACKUP_CREATE', SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RAISE;
  END CREATE_SNAPSHOT;

  PROCEDURE RESTORE_SNAPSHOT(
      P_SNAPSHOT_ID IN NUMBER,
      P_ACTOR       IN VARCHAR2
  ) IS
    V_ACTOR VARCHAR2(64) := NORMALIZE_TEXT(P_ACTOR, 64);
  BEGIN
    ASSERT_SNAPSHOT(P_SNAPSHOT_ID);

    DELETE FROM MAINT_TASK;
    DELETE FROM ALARM_LOG;
    DELETE FROM CABINET_DOOR_LOG;
    DELETE FROM TS_RAW_DATA;
    DELETE FROM TS_RAW_DATA_DAY_ARCHIVE;
    DELETE FROM MEASURE_POINT;
    DELETE FROM POWER_CIRCUIT;
    DELETE FROM BOX_TRANSFORMER;

    INSERT INTO BOX_TRANSFORMER (
      ID, TRANSFORMER_CODE, NAME, TRANSFORMER_TYPE, RATED_CAPACITY_KVA,
      RATED_VOLTAGE_RATIO, COMMISSION_DATE, MANUFACTURER, OIL_LEVEL,
      LOCATION, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      ID, TRANSFORMER_CODE, NAME, TRANSFORMER_TYPE, RATED_CAPACITY_KVA,
      RATED_VOLTAGE_RATIO, COMMISSION_DATE, MANUFACTURER, OIL_LEVEL,
      LOCATION, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM DATA_SNAPSHOT_TRANSFORMER
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO POWER_CIRCUIT (
      ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION, RATED_VOLTAGE_KV,
      RATED_CURRENT_A, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION, RATED_VOLTAGE_KV,
      RATED_CURRENT_A, STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM DATA_SNAPSHOT_CIRCUIT
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO MEASURE_POINT (
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
      MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
      STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    )
    SELECT
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
      MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
      STATUS, IS_DELETED, CREATED_AT, UPDATED_AT
    FROM DATA_SNAPSHOT_POINT
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO TS_RAW_DATA (
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL,
      QUALITY_FLAG, CREATED_AT
    )
    SELECT
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL,
      QUALITY_FLAG, CREATED_AT
    FROM DATA_SNAPSHOT_RAW_DATA
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO TS_RAW_DATA_DAY_ARCHIVE (
      ID, ARCHIVE_DAY, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, DISPLAY_VAL,
      AVG_VAL, MIN_VAL, MAX_VAL, SAMPLE_COUNT, MAX_QUALITY_FLAG, CREATED_AT
    )
    SELECT
      ID, ARCHIVE_DAY, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, DISPLAY_VAL,
      AVG_VAL, MIN_VAL, MAX_VAL, SAMPLE_COUNT, MAX_QUALITY_FLAG, CREATED_AT
    FROM DATA_SNAPSHOT_DAY_ARCHIVE
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO CABINET_DOOR_LOG (
      ID, TRANSFORMER_ID, POINT_ID, EVENT_TYPE, EVENT_TIME, DOOR_STATUS,
      NOTE, CREATED_AT
    )
    SELECT
      ID, TRANSFORMER_ID, POINT_ID, EVENT_TYPE, EVENT_TIME, DOOR_STATUS,
      NOTE, CREATED_AT
    FROM DATA_SNAPSHOT_DOOR_LOG
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO ALARM_LOG (
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, ALARM_TYPE, ALARM_LEVEL,
      START_TIME, END_TIME, START_VAL, END_VAL, STATUS, CREATED_AT
    )
    SELECT
      ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, ALARM_TYPE, ALARM_LEVEL,
      START_TIME, END_TIME, START_VAL, END_VAL, STATUS, CREATED_AT
    FROM DATA_SNAPSHOT_ALARM
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    INSERT INTO MAINT_TASK (
      TASK_ID, ALARM_ID, STATUS, ASSIGNEE, FEEDBACK, CREATED_AT,
      UPDATED_AT, FINISHED_AT
    )
    SELECT
      TASK_ID, ALARM_ID, STATUS, ASSIGNEE, FEEDBACK, CREATED_AT,
      UPDATED_AT, FINISHED_AT
    FROM DATA_SNAPSHOT_TASK
    WHERE SNAPSHOT_ID = P_SNAPSHOT_ID;

    UPDATE BOX_TRANSFORMER BT
    SET (STATUS, IS_DELETED, UPDATED_AT) = (
      SELECT S.STATUS, S.IS_DELETED, S.UPDATED_AT
      FROM DATA_SNAPSHOT_TRANSFORMER S
      WHERE S.SNAPSHOT_ID = P_SNAPSHOT_ID
        AND S.ID = BT.ID
    )
    WHERE EXISTS (
      SELECT 1
      FROM DATA_SNAPSHOT_TRANSFORMER S
      WHERE S.SNAPSHOT_ID = P_SNAPSHOT_ID
        AND S.ID = BT.ID
    );

    UPDATE POWER_CIRCUIT PC
    SET (STATUS, IS_DELETED, UPDATED_AT) = (
      SELECT S.STATUS, S.IS_DELETED, S.UPDATED_AT
      FROM DATA_SNAPSHOT_CIRCUIT S
      WHERE S.SNAPSHOT_ID = P_SNAPSHOT_ID
        AND S.ID = PC.ID
    )
    WHERE EXISTS (
      SELECT 1
      FROM DATA_SNAPSHOT_CIRCUIT S
      WHERE S.SNAPSHOT_ID = P_SNAPSHOT_ID
        AND S.ID = PC.ID
    );

    UPDATE SIM_CONTROL
    SET
      RUNNING = 0,
      ANOMALY_ENABLED = 0,
      STARTED_AT = NULL,
      LAST_WRITE_AT = (SELECT MAX(SAMPLE_TIME) FROM TS_RAW_DATA),
      WRITE_COUNT = (SELECT COUNT(1) FROM TS_RAW_DATA),
      ALARM_COUNT = (SELECT COUNT(1) FROM ALARM_LOG),
      TASK_COUNT = (SELECT COUNT(1) FROM MAINT_TASK),
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;

    UPDATE DATA_SNAPSHOT
    SET
      RESTORED_BY = V_ACTOR,
      RESTORED_AT = LOCALTIMESTAMP
    WHERE ID = P_SNAPSHOT_ID;

    BUMP_ALL_SEQUENCES;

    COMMIT;
    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'BACKUP_RESTORE',
      'Restored data snapshot ' || P_SNAPSHOT_ID,
      'actor=' || NVL(V_ACTOR, 'unknown')
    );
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PKG_PSM_LOG.WRITE_LOG('ERROR', 'BACKUP_RESTORE', SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RAISE;
  END RESTORE_SNAPSHOT;
END PKG_PSM_BACKUP;
/

CREATE OR REPLACE PACKAGE PKG_PSM_ASSET AS
  PROCEDURE CREATE_TRANSFORMER(
      P_TRANSFORMER_CODE   IN VARCHAR2,
      P_NAME               IN VARCHAR2,
      P_RATED_CAPACITY_KVA IN NUMBER,
      P_RATED_VOLTAGE_RATIO IN VARCHAR2,
      P_COMMISSION_DATE    IN DATE,
      P_MANUFACTURER       IN VARCHAR2,
      P_OIL_LEVEL          IN NUMBER,
      P_LOCATION           IN VARCHAR2,
      P_STATUS             IN NUMBER,
      P_TRANSFORMER_ID     OUT NUMBER
  );

  PROCEDURE UPDATE_TRANSFORMER(
      P_TRANSFORMER_ID     IN NUMBER,
      P_TRANSFORMER_CODE   IN VARCHAR2,
      P_NAME               IN VARCHAR2,
      P_RATED_CAPACITY_KVA IN NUMBER,
      P_RATED_VOLTAGE_RATIO IN VARCHAR2,
      P_COMMISSION_DATE    IN DATE,
      P_MANUFACTURER       IN VARCHAR2,
      P_OIL_LEVEL          IN NUMBER,
      P_LOCATION           IN VARCHAR2,
      P_STATUS             IN NUMBER
  );

  PROCEDURE DELETE_TRANSFORMER(P_TRANSFORMER_ID IN NUMBER);

  PROCEDURE CREATE_CIRCUIT(
      P_TRANSFORMER_ID   IN NUMBER,
      P_CIRCUIT_CODE     IN VARCHAR2,
      P_NAME             IN VARCHAR2,
      P_DIRECTION        IN VARCHAR2,
      P_RATED_VOLTAGE_KV IN NUMBER,
      P_RATED_CURRENT_A  IN NUMBER,
      P_STATUS           IN NUMBER,
      P_CIRCUIT_ID       OUT NUMBER
  );

  PROCEDURE UPDATE_CIRCUIT(
      P_CIRCUIT_ID       IN NUMBER,
      P_CIRCUIT_CODE     IN VARCHAR2,
      P_NAME             IN VARCHAR2,
      P_DIRECTION        IN VARCHAR2,
      P_RATED_VOLTAGE_KV IN NUMBER,
      P_RATED_CURRENT_A  IN NUMBER,
      P_STATUS           IN NUMBER
  );

  PROCEDURE DELETE_CIRCUIT(P_CIRCUIT_ID IN NUMBER);

  PROCEDURE CREATE_POINT(
      P_TRANSFORMER_ID IN NUMBER,
      P_CIRCUIT_ID     IN NUMBER,
      P_POINT_CODE     IN VARCHAR2,
      P_POINT_NAME     IN VARCHAR2,
      P_POINT_GROUP    IN VARCHAR2,
      P_MEASURE_TYPE   IN VARCHAR2,
      P_PHASE_CODE     IN VARCHAR2,
      P_UNIT           IN VARCHAR2,
      P_MIN_LIMIT      IN NUMBER,
      P_MAX_LIMIT      IN NUMBER,
      P_RATE_LIMIT     IN NUMBER,
      P_STATUS         IN NUMBER,
      P_POINT_ID       OUT NUMBER
  );

  PROCEDURE UPDATE_POINT(
      P_POINT_ID       IN NUMBER,
      P_CIRCUIT_ID     IN NUMBER,
      P_POINT_CODE     IN VARCHAR2,
      P_POINT_NAME     IN VARCHAR2,
      P_POINT_GROUP    IN VARCHAR2,
      P_MEASURE_TYPE   IN VARCHAR2,
      P_PHASE_CODE     IN VARCHAR2,
      P_UNIT           IN VARCHAR2,
      P_MIN_LIMIT      IN NUMBER,
      P_MAX_LIMIT      IN NUMBER,
      P_RATE_LIMIT     IN NUMBER,
      P_STATUS         IN NUMBER
  );

  PROCEDURE DELETE_POINT(P_POINT_ID IN NUMBER);
END PKG_PSM_ASSET;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_ASSET AS
  FUNCTION NORMALIZE_TEXT(P_TEXT IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN NULLIF(TRIM(P_TEXT), '');
  END NORMALIZE_TEXT;

  FUNCTION NORMALIZE_UPPER(P_TEXT IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN UPPER(NORMALIZE_TEXT(P_TEXT));
  END NORMALIZE_UPPER;

  PROCEDURE ASSERT_REQUIRED(P_VALUE IN VARCHAR2, P_LABEL IN VARCHAR2) IS
  BEGIN
    IF P_VALUE IS NULL THEN
      RAISE_APPLICATION_ERROR(-20500, P_LABEL || ' is required.');
    END IF;
  END ASSERT_REQUIRED;

  PROCEDURE ASSERT_TRANSFORMER_STATUS(P_STATUS IN NUMBER) IS
  BEGIN
    IF P_STATUS IS NULL OR P_STATUS NOT IN (0, 1, 2) THEN
      RAISE_APPLICATION_ERROR(-20501, 'Invalid transformer status.');
    END IF;
  END ASSERT_TRANSFORMER_STATUS;

  PROCEDURE ASSERT_CIRCUIT_STATUS(P_STATUS IN NUMBER) IS
  BEGIN
    IF P_STATUS IS NULL OR P_STATUS NOT IN (0, 1, 2) THEN
      RAISE_APPLICATION_ERROR(-20502, 'Invalid circuit status.');
    END IF;
  END ASSERT_CIRCUIT_STATUS;

  PROCEDURE ASSERT_POINT_STATUS(P_STATUS IN NUMBER) IS
  BEGIN
    IF P_STATUS IS NULL OR P_STATUS NOT IN (0, 1) THEN
      RAISE_APPLICATION_ERROR(-20503, 'Invalid measure point status.');
    END IF;
  END ASSERT_POINT_STATUS;

  PROCEDURE ASSERT_ACTIVE_TRANSFORMER(P_TRANSFORMER_ID IN NUMBER) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM BOX_TRANSFORMER
    WHERE ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    IF V_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20504, 'Transformer does not exist.');
    END IF;
  END ASSERT_ACTIVE_TRANSFORMER;

  PROCEDURE ASSERT_ACTIVE_CIRCUIT(P_CIRCUIT_ID IN NUMBER, P_TRANSFORMER_ID IN NUMBER DEFAULT NULL) IS
    V_COUNT NUMBER;
  BEGIN
    IF P_CIRCUIT_ID IS NULL THEN
      RAISE_APPLICATION_ERROR(-20505, 'Circuit does not exist.');
    END IF;

    SELECT COUNT(1)
    INTO V_COUNT
    FROM POWER_CIRCUIT
    WHERE ID = P_CIRCUIT_ID
      AND IS_DELETED = 0
      AND (P_TRANSFORMER_ID IS NULL OR TRANSFORMER_ID = P_TRANSFORMER_ID);

    IF V_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20505, 'Circuit does not exist.');
    END IF;
  END ASSERT_ACTIVE_CIRCUIT;

  PROCEDURE ASSERT_ACTIVE_POINT(P_POINT_ID IN NUMBER) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM MEASURE_POINT
    WHERE ID = P_POINT_ID
      AND IS_DELETED = 0;

    IF V_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20506, 'Measure point does not exist.');
    END IF;
  END ASSERT_ACTIVE_POINT;

  PROCEDURE VALIDATE_DIRECTION(P_DIRECTION IN VARCHAR2) IS
  BEGIN
    IF P_DIRECTION IS NULL OR P_DIRECTION NOT IN ('INCOMING', 'OUTGOING') THEN
      RAISE_APPLICATION_ERROR(-20507, 'Invalid circuit direction.');
    END IF;
  END VALIDATE_DIRECTION;

  PROCEDURE VALIDATE_TRANSFORMER_UNIQUENESS(
      P_TRANSFORMER_ID IN NUMBER,
      P_TRANSFORMER_CODE IN VARCHAR2,
      P_NAME IN VARCHAR2
  ) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM BOX_TRANSFORMER
    WHERE IS_DELETED = 0
      AND ID != NVL(P_TRANSFORMER_ID, -1)
      AND UPPER(TRIM(TRANSFORMER_CODE)) = P_TRANSFORMER_CODE;

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20508, 'Transformer code already exists.');
    END IF;

    SELECT COUNT(1)
    INTO V_COUNT
    FROM BOX_TRANSFORMER
    WHERE IS_DELETED = 0
      AND ID != NVL(P_TRANSFORMER_ID, -1)
      AND UPPER(TRIM(NAME)) = UPPER(TRIM(P_NAME));

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20509, 'Transformer name already exists.');
    END IF;
  END VALIDATE_TRANSFORMER_UNIQUENESS;

  PROCEDURE VALIDATE_CIRCUIT_UNIQUENESS(
      P_CIRCUIT_ID IN NUMBER,
      P_TRANSFORMER_ID IN NUMBER,
      P_CIRCUIT_CODE IN VARCHAR2,
      P_NAME IN VARCHAR2,
      P_DIRECTION IN VARCHAR2
  ) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM POWER_CIRCUIT
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0
      AND ID != NVL(P_CIRCUIT_ID, -1)
      AND UPPER(TRIM(CIRCUIT_CODE)) = P_CIRCUIT_CODE;

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20510, 'Circuit code already exists under this transformer.');
    END IF;

    SELECT COUNT(1)
    INTO V_COUNT
    FROM POWER_CIRCUIT
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0
      AND ID != NVL(P_CIRCUIT_ID, -1)
      AND UPPER(TRIM(NAME)) = UPPER(TRIM(P_NAME));

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20511, 'Circuit name already exists under this transformer.');
    END IF;

    IF P_DIRECTION = 'INCOMING' THEN
      SELECT COUNT(1)
      INTO V_COUNT
      FROM POWER_CIRCUIT
      WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
        AND IS_DELETED = 0
        AND ID != NVL(P_CIRCUIT_ID, -1)
        AND DIRECTION = 'INCOMING';

      IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20512, 'Only one active incoming circuit is allowed per transformer.');
      END IF;
    END IF;
  END VALIDATE_CIRCUIT_UNIQUENESS;

  PROCEDURE VALIDATE_POINT_UNIQUENESS(
      P_POINT_ID IN NUMBER,
      P_TRANSFORMER_ID IN NUMBER,
      P_POINT_CODE IN VARCHAR2,
      P_POINT_NAME IN VARCHAR2
  ) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM MEASURE_POINT
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0
      AND ID != NVL(P_POINT_ID, -1)
      AND UPPER(TRIM(POINT_CODE)) = P_POINT_CODE;

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20513, 'Measure point code already exists under this transformer.');
    END IF;

    SELECT COUNT(1)
    INTO V_COUNT
    FROM MEASURE_POINT
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0
      AND ID != NVL(P_POINT_ID, -1)
      AND UPPER(TRIM(POINT_NAME)) = UPPER(TRIM(P_POINT_NAME));

    IF V_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20514, 'Measure point name already exists under this transformer.');
    END IF;
  END VALIDATE_POINT_UNIQUENESS;

  PROCEDURE VALIDATE_POINT_SCOPE(
      P_TRANSFORMER_ID IN NUMBER,
      P_CIRCUIT_ID IN NUMBER,
      P_POINT_GROUP IN VARCHAR2
  ) IS
    V_DIRECTION VARCHAR2(20);
  BEGIN
    IF P_CIRCUIT_ID IS NULL THEN
      IF P_POINT_GROUP NOT IN ('TRANSFORMER', 'CABINET') THEN
        RAISE_APPLICATION_ERROR(-20515, 'Transformer-level points must use TRANSFORMER or CABINET point groups.');
      END IF;
      RETURN;
    END IF;

    SELECT DIRECTION
    INTO V_DIRECTION
    FROM POWER_CIRCUIT
    WHERE ID = P_CIRCUIT_ID
      AND TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    IF P_POINT_GROUP IN ('TRANSFORMER', 'CABINET') THEN
      RAISE_APPLICATION_ERROR(-20516, 'Transformer or cabinet points cannot be attached to a circuit.');
    END IF;

    IF V_DIRECTION = 'INCOMING' AND P_POINT_GROUP != 'ELECTRIC_IN' THEN
      RAISE_APPLICATION_ERROR(-20517, 'Incoming circuit points must use ELECTRIC_IN point group.');
    END IF;

    IF V_DIRECTION = 'OUTGOING' AND P_POINT_GROUP != 'ELECTRIC_OUT' THEN
      RAISE_APPLICATION_ERROR(-20518, 'Outgoing circuit points must use ELECTRIC_OUT point group.');
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20505, 'Circuit does not exist.');
  END VALIDATE_POINT_SCOPE;

  PROCEDURE CREATE_TRANSFORMER(
      P_TRANSFORMER_CODE   IN VARCHAR2,
      P_NAME               IN VARCHAR2,
      P_RATED_CAPACITY_KVA IN NUMBER,
      P_RATED_VOLTAGE_RATIO IN VARCHAR2,
      P_COMMISSION_DATE    IN DATE,
      P_MANUFACTURER       IN VARCHAR2,
      P_OIL_LEVEL          IN NUMBER,
      P_LOCATION           IN VARCHAR2,
      P_STATUS             IN NUMBER,
      P_TRANSFORMER_ID     OUT NUMBER
  ) IS
    V_CODE                  VARCHAR2(64) := NORMALIZE_UPPER(P_TRANSFORMER_CODE);
    V_NAME                  VARCHAR2(100) := NORMALIZE_TEXT(P_NAME);
    V_RATED_VOLTAGE_RATIO   VARCHAR2(50) := NORMALIZE_TEXT(P_RATED_VOLTAGE_RATIO);
    V_MANUFACTURER          VARCHAR2(100) := NORMALIZE_TEXT(P_MANUFACTURER);
    V_LOCATION              VARCHAR2(200) := NORMALIZE_TEXT(P_LOCATION);
    V_STATUS                NUMBER := NVL(P_STATUS, 0);
  BEGIN
    ASSERT_REQUIRED(V_CODE, 'Transformer code');
    ASSERT_REQUIRED(V_NAME, 'Transformer name');
    ASSERT_TRANSFORMER_STATUS(V_STATUS);
    VALIDATE_TRANSFORMER_UNIQUENESS(NULL, V_CODE, V_NAME);

    P_TRANSFORMER_ID := SEQ_BOX_TRANSFORMER.NEXTVAL;
    INSERT INTO BOX_TRANSFORMER (
      ID,
      TRANSFORMER_CODE,
      NAME,
      TRANSFORMER_TYPE,
      RATED_CAPACITY_KVA,
      RATED_VOLTAGE_RATIO,
      COMMISSION_DATE,
      MANUFACTURER,
      OIL_LEVEL,
      LOCATION,
      STATUS,
      IS_DELETED,
      CREATED_AT,
      UPDATED_AT
    ) VALUES (
      P_TRANSFORMER_ID,
      V_CODE,
      V_NAME,
      'BOX_TRANSFORMER',
      P_RATED_CAPACITY_KVA,
      V_RATED_VOLTAGE_RATIO,
      P_COMMISSION_DATE,
      V_MANUFACTURER,
      P_OIL_LEVEL,
      V_LOCATION,
      V_STATUS,
      0,
      LOCALTIMESTAMP,
      NULL
    );

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END CREATE_TRANSFORMER;

  PROCEDURE UPDATE_TRANSFORMER(
      P_TRANSFORMER_ID     IN NUMBER,
      P_TRANSFORMER_CODE   IN VARCHAR2,
      P_NAME               IN VARCHAR2,
      P_RATED_CAPACITY_KVA IN NUMBER,
      P_RATED_VOLTAGE_RATIO IN VARCHAR2,
      P_COMMISSION_DATE    IN DATE,
      P_MANUFACTURER       IN VARCHAR2,
      P_OIL_LEVEL          IN NUMBER,
      P_LOCATION           IN VARCHAR2,
      P_STATUS             IN NUMBER
  ) IS
    V_CODE                  VARCHAR2(64) := NORMALIZE_UPPER(P_TRANSFORMER_CODE);
    V_NAME                  VARCHAR2(100) := NORMALIZE_TEXT(P_NAME);
    V_RATED_VOLTAGE_RATIO   VARCHAR2(50) := NORMALIZE_TEXT(P_RATED_VOLTAGE_RATIO);
    V_MANUFACTURER          VARCHAR2(100) := NORMALIZE_TEXT(P_MANUFACTURER);
    V_LOCATION              VARCHAR2(200) := NORMALIZE_TEXT(P_LOCATION);
  BEGIN
    ASSERT_ACTIVE_TRANSFORMER(P_TRANSFORMER_ID);
    ASSERT_REQUIRED(V_CODE, 'Transformer code');
    ASSERT_REQUIRED(V_NAME, 'Transformer name');
    ASSERT_TRANSFORMER_STATUS(P_STATUS);
    VALIDATE_TRANSFORMER_UNIQUENESS(P_TRANSFORMER_ID, V_CODE, V_NAME);

    UPDATE BOX_TRANSFORMER
    SET
      TRANSFORMER_CODE = V_CODE,
      NAME = V_NAME,
      RATED_CAPACITY_KVA = P_RATED_CAPACITY_KVA,
      RATED_VOLTAGE_RATIO = V_RATED_VOLTAGE_RATIO,
      COMMISSION_DATE = P_COMMISSION_DATE,
      MANUFACTURER = V_MANUFACTURER,
      OIL_LEVEL = P_OIL_LEVEL,
      LOCATION = V_LOCATION,
      STATUS = P_STATUS,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END UPDATE_TRANSFORMER;

  PROCEDURE DELETE_TRANSFORMER(P_TRANSFORMER_ID IN NUMBER) IS
  BEGIN
    ASSERT_ACTIVE_TRANSFORMER(P_TRANSFORMER_ID);

    UPDATE MEASURE_POINT
    SET
      IS_DELETED = 1,
      STATUS = 1,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    UPDATE POWER_CIRCUIT
    SET
      IS_DELETED = 1,
      STATUS = 2,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE TRANSFORMER_ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    UPDATE BOX_TRANSFORMER
    SET
      IS_DELETED = 1,
      STATUS = 2,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_TRANSFORMER_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END DELETE_TRANSFORMER;

  PROCEDURE CREATE_CIRCUIT(
      P_TRANSFORMER_ID   IN NUMBER,
      P_CIRCUIT_CODE     IN VARCHAR2,
      P_NAME             IN VARCHAR2,
      P_DIRECTION        IN VARCHAR2,
      P_RATED_VOLTAGE_KV IN NUMBER,
      P_RATED_CURRENT_A  IN NUMBER,
      P_STATUS           IN NUMBER,
      P_CIRCUIT_ID       OUT NUMBER
  ) IS
    V_CODE      VARCHAR2(64) := NORMALIZE_UPPER(P_CIRCUIT_CODE);
    V_NAME      VARCHAR2(100) := NORMALIZE_TEXT(P_NAME);
    V_DIRECTION VARCHAR2(20) := NORMALIZE_UPPER(P_DIRECTION);
    V_STATUS    NUMBER := NVL(P_STATUS, 0);
  BEGIN
    ASSERT_ACTIVE_TRANSFORMER(P_TRANSFORMER_ID);
    ASSERT_REQUIRED(V_CODE, 'Circuit code');
    ASSERT_REQUIRED(V_NAME, 'Circuit name');
    VALIDATE_DIRECTION(V_DIRECTION);
    ASSERT_CIRCUIT_STATUS(V_STATUS);
    VALIDATE_CIRCUIT_UNIQUENESS(NULL, P_TRANSFORMER_ID, V_CODE, V_NAME, V_DIRECTION);

    P_CIRCUIT_ID := SEQ_POWER_CIRCUIT.NEXTVAL;
    INSERT INTO POWER_CIRCUIT (
      ID,
      TRANSFORMER_ID,
      CIRCUIT_CODE,
      NAME,
      DIRECTION,
      RATED_VOLTAGE_KV,
      RATED_CURRENT_A,
      STATUS,
      IS_DELETED,
      CREATED_AT,
      UPDATED_AT
    ) VALUES (
      P_CIRCUIT_ID,
      P_TRANSFORMER_ID,
      V_CODE,
      V_NAME,
      V_DIRECTION,
      P_RATED_VOLTAGE_KV,
      P_RATED_CURRENT_A,
      V_STATUS,
      0,
      LOCALTIMESTAMP,
      NULL
    );

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END CREATE_CIRCUIT;

  PROCEDURE UPDATE_CIRCUIT(
      P_CIRCUIT_ID       IN NUMBER,
      P_CIRCUIT_CODE     IN VARCHAR2,
      P_NAME             IN VARCHAR2,
      P_DIRECTION        IN VARCHAR2,
      P_RATED_VOLTAGE_KV IN NUMBER,
      P_RATED_CURRENT_A  IN NUMBER,
      P_STATUS           IN NUMBER
  ) IS
    V_TRANSFORMER_ID NUMBER;
    V_CODE           VARCHAR2(64) := NORMALIZE_UPPER(P_CIRCUIT_CODE);
    V_NAME           VARCHAR2(100) := NORMALIZE_TEXT(P_NAME);
    V_DIRECTION      VARCHAR2(20) := NORMALIZE_UPPER(P_DIRECTION);
  BEGIN
    ASSERT_ACTIVE_CIRCUIT(P_CIRCUIT_ID);
    ASSERT_REQUIRED(V_CODE, 'Circuit code');
    ASSERT_REQUIRED(V_NAME, 'Circuit name');
    VALIDATE_DIRECTION(V_DIRECTION);
    ASSERT_CIRCUIT_STATUS(P_STATUS);

    SELECT TRANSFORMER_ID
    INTO V_TRANSFORMER_ID
    FROM POWER_CIRCUIT
    WHERE ID = P_CIRCUIT_ID
      AND IS_DELETED = 0
    FOR UPDATE;

    VALIDATE_CIRCUIT_UNIQUENESS(P_CIRCUIT_ID, V_TRANSFORMER_ID, V_CODE, V_NAME, V_DIRECTION);

    UPDATE POWER_CIRCUIT
    SET
      CIRCUIT_CODE = V_CODE,
      NAME = V_NAME,
      DIRECTION = V_DIRECTION,
      RATED_VOLTAGE_KV = P_RATED_VOLTAGE_KV,
      RATED_CURRENT_A = P_RATED_CURRENT_A,
      STATUS = P_STATUS,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_CIRCUIT_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END UPDATE_CIRCUIT;

  PROCEDURE DELETE_CIRCUIT(P_CIRCUIT_ID IN NUMBER) IS
  BEGIN
    ASSERT_ACTIVE_CIRCUIT(P_CIRCUIT_ID);

    UPDATE MEASURE_POINT
    SET
      IS_DELETED = 1,
      STATUS = 1,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE CIRCUIT_ID = P_CIRCUIT_ID
      AND IS_DELETED = 0;

    UPDATE POWER_CIRCUIT
    SET
      IS_DELETED = 1,
      STATUS = 2,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_CIRCUIT_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END DELETE_CIRCUIT;

  PROCEDURE CREATE_POINT(
      P_TRANSFORMER_ID IN NUMBER,
      P_CIRCUIT_ID     IN NUMBER,
      P_POINT_CODE     IN VARCHAR2,
      P_POINT_NAME     IN VARCHAR2,
      P_POINT_GROUP    IN VARCHAR2,
      P_MEASURE_TYPE   IN VARCHAR2,
      P_PHASE_CODE     IN VARCHAR2,
      P_UNIT           IN VARCHAR2,
      P_MIN_LIMIT      IN NUMBER,
      P_MAX_LIMIT      IN NUMBER,
      P_RATE_LIMIT     IN NUMBER,
      P_STATUS         IN NUMBER,
      P_POINT_ID       OUT NUMBER
  ) IS
    V_POINT_CODE   VARCHAR2(64) := NORMALIZE_UPPER(P_POINT_CODE);
    V_POINT_NAME   VARCHAR2(100) := NORMALIZE_TEXT(P_POINT_NAME);
    V_POINT_GROUP  VARCHAR2(50) := NORMALIZE_UPPER(P_POINT_GROUP);
    V_MEASURE_TYPE VARCHAR2(50) := NORMALIZE_UPPER(P_MEASURE_TYPE);
    V_PHASE_CODE   VARCHAR2(20) := NVL(NORMALIZE_UPPER(P_PHASE_CODE), 'NONE');
    V_UNIT         VARCHAR2(20) := NORMALIZE_TEXT(P_UNIT);
    V_STATUS       NUMBER := NVL(P_STATUS, 0);
  BEGIN
    ASSERT_ACTIVE_TRANSFORMER(P_TRANSFORMER_ID);
    ASSERT_REQUIRED(V_POINT_CODE, 'Measure point code');
    ASSERT_REQUIRED(V_POINT_NAME, 'Measure point name');
    ASSERT_REQUIRED(V_POINT_GROUP, 'Point group');
    ASSERT_REQUIRED(V_MEASURE_TYPE, 'Measure type');
    ASSERT_REQUIRED(V_PHASE_CODE, 'Phase code');
    ASSERT_POINT_STATUS(V_STATUS);

    IF P_CIRCUIT_ID IS NOT NULL THEN
      ASSERT_ACTIVE_CIRCUIT(P_CIRCUIT_ID, P_TRANSFORMER_ID);
    END IF;

    VALIDATE_POINT_SCOPE(P_TRANSFORMER_ID, P_CIRCUIT_ID, V_POINT_GROUP);
    VALIDATE_POINT_UNIQUENESS(NULL, P_TRANSFORMER_ID, V_POINT_CODE, V_POINT_NAME);

    P_POINT_ID := SEQ_MEASURE_POINT.NEXTVAL;
    INSERT INTO MEASURE_POINT (
      ID,
      TRANSFORMER_ID,
      CIRCUIT_ID,
      POINT_CODE,
      POINT_NAME,
      POINT_GROUP,
      MEASURE_TYPE,
      PHASE_CODE,
      UNIT,
      MIN_LIMIT,
      MAX_LIMIT,
      RATE_LIMIT,
      STATUS,
      IS_DELETED,
      CREATED_AT,
      UPDATED_AT
    ) VALUES (
      P_POINT_ID,
      P_TRANSFORMER_ID,
      P_CIRCUIT_ID,
      V_POINT_CODE,
      V_POINT_NAME,
      V_POINT_GROUP,
      V_MEASURE_TYPE,
      V_PHASE_CODE,
      V_UNIT,
      P_MIN_LIMIT,
      P_MAX_LIMIT,
      P_RATE_LIMIT,
      V_STATUS,
      0,
      LOCALTIMESTAMP,
      NULL
    );

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END CREATE_POINT;

  PROCEDURE UPDATE_POINT(
      P_POINT_ID       IN NUMBER,
      P_CIRCUIT_ID     IN NUMBER,
      P_POINT_CODE     IN VARCHAR2,
      P_POINT_NAME     IN VARCHAR2,
      P_POINT_GROUP    IN VARCHAR2,
      P_MEASURE_TYPE   IN VARCHAR2,
      P_PHASE_CODE     IN VARCHAR2,
      P_UNIT           IN VARCHAR2,
      P_MIN_LIMIT      IN NUMBER,
      P_MAX_LIMIT      IN NUMBER,
      P_RATE_LIMIT     IN NUMBER,
      P_STATUS         IN NUMBER
  ) IS
    V_TRANSFORMER_ID NUMBER;
    V_POINT_CODE     VARCHAR2(64) := NORMALIZE_UPPER(P_POINT_CODE);
    V_POINT_NAME     VARCHAR2(100) := NORMALIZE_TEXT(P_POINT_NAME);
    V_POINT_GROUP    VARCHAR2(50) := NORMALIZE_UPPER(P_POINT_GROUP);
    V_MEASURE_TYPE   VARCHAR2(50) := NORMALIZE_UPPER(P_MEASURE_TYPE);
    V_PHASE_CODE     VARCHAR2(20) := NVL(NORMALIZE_UPPER(P_PHASE_CODE), 'NONE');
    V_UNIT           VARCHAR2(20) := NORMALIZE_TEXT(P_UNIT);
  BEGIN
    ASSERT_ACTIVE_POINT(P_POINT_ID);
    ASSERT_REQUIRED(V_POINT_CODE, 'Measure point code');
    ASSERT_REQUIRED(V_POINT_NAME, 'Measure point name');
    ASSERT_REQUIRED(V_POINT_GROUP, 'Point group');
    ASSERT_REQUIRED(V_MEASURE_TYPE, 'Measure type');
    ASSERT_REQUIRED(V_PHASE_CODE, 'Phase code');
    ASSERT_POINT_STATUS(P_STATUS);

    SELECT TRANSFORMER_ID
    INTO V_TRANSFORMER_ID
    FROM MEASURE_POINT
    WHERE ID = P_POINT_ID
      AND IS_DELETED = 0
    FOR UPDATE;

    IF P_CIRCUIT_ID IS NOT NULL THEN
      ASSERT_ACTIVE_CIRCUIT(P_CIRCUIT_ID, V_TRANSFORMER_ID);
    END IF;

    VALIDATE_POINT_SCOPE(V_TRANSFORMER_ID, P_CIRCUIT_ID, V_POINT_GROUP);
    VALIDATE_POINT_UNIQUENESS(P_POINT_ID, V_TRANSFORMER_ID, V_POINT_CODE, V_POINT_NAME);

    UPDATE MEASURE_POINT
    SET
      CIRCUIT_ID = P_CIRCUIT_ID,
      POINT_CODE = V_POINT_CODE,
      POINT_NAME = V_POINT_NAME,
      POINT_GROUP = V_POINT_GROUP,
      MEASURE_TYPE = V_MEASURE_TYPE,
      PHASE_CODE = V_PHASE_CODE,
      UNIT = V_UNIT,
      MIN_LIMIT = P_MIN_LIMIT,
      MAX_LIMIT = P_MAX_LIMIT,
      RATE_LIMIT = P_RATE_LIMIT,
      STATUS = P_STATUS,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_POINT_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END UPDATE_POINT;

  PROCEDURE DELETE_POINT(P_POINT_ID IN NUMBER) IS
  BEGIN
    ASSERT_ACTIVE_POINT(P_POINT_ID);

    UPDATE MEASURE_POINT
    SET
      IS_DELETED = 1,
      STATUS = 1,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = P_POINT_ID
      AND IS_DELETED = 0;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END DELETE_POINT;
END PKG_PSM_ASSET;
/

CREATE OR REPLACE TRIGGER TRG_PSM_ALARM_OPEN_STATUS
AFTER INSERT ON ALARM_LOG
FOR EACH ROW
BEGIN
  IF :NEW.STATUS = 0 AND UPPER(NVL(:NEW.ALARM_LEVEL, '')) = 'SERIOUS' THEN
    UPDATE BOX_TRANSFORMER
    SET STATUS = 1,
        UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = :NEW.TRANSFORMER_ID
      AND IS_DELETED = 0
      AND STATUS = 0;

    IF :NEW.CIRCUIT_ID IS NOT NULL THEN
      UPDATE POWER_CIRCUIT
      SET STATUS = 1,
          UPDATED_AT = LOCALTIMESTAMP
      WHERE ID = :NEW.CIRCUIT_ID
        AND IS_DELETED = 0
        AND STATUS = 0;
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PSM_TASK_COMPLETE_STATUS
AFTER UPDATE OF STATUS ON MAINT_TASK
FOR EACH ROW
DECLARE
  V_TRANSFORMER_ID NUMBER;
  V_CIRCUIT_ID NUMBER;
  V_ACTIVE_COUNT NUMBER;
BEGIN
  IF :NEW.STATUS = 2 AND NVL(:OLD.STATUS, -1) != 2 THEN
    SELECT TRANSFORMER_ID, CIRCUIT_ID
    INTO V_TRANSFORMER_ID, V_CIRCUIT_ID
    FROM ALARM_LOG
    WHERE ID = :NEW.ALARM_ID;

    IF V_CIRCUIT_ID IS NOT NULL THEN
      SELECT COUNT(1)
      INTO V_ACTIVE_COUNT
      FROM ALARM_LOG A
      LEFT JOIN MEASURE_POINT MP ON MP.ID = A.POINT_ID
      WHERE A.CIRCUIT_ID = V_CIRCUIT_ID
        AND A.STATUS = 0
        AND (A.POINT_ID IS NULL OR NVL(MP.IS_DELETED, 0) = 0);

      IF V_ACTIVE_COUNT = 0 THEN
        UPDATE POWER_CIRCUIT
        SET STATUS = 0,
            UPDATED_AT = LOCALTIMESTAMP
        WHERE ID = V_CIRCUIT_ID
          AND IS_DELETED = 0
          AND STATUS = 1;
      END IF;
    END IF;

    SELECT COUNT(1)
    INTO V_ACTIVE_COUNT
    FROM ALARM_LOG A
    LEFT JOIN POWER_CIRCUIT PC ON PC.ID = A.CIRCUIT_ID
    LEFT JOIN MEASURE_POINT MP ON MP.ID = A.POINT_ID
    WHERE A.TRANSFORMER_ID = V_TRANSFORMER_ID
      AND A.STATUS = 0
      AND (A.CIRCUIT_ID IS NULL OR NVL(PC.IS_DELETED, 0) = 0)
      AND (A.POINT_ID IS NULL OR NVL(MP.IS_DELETED, 0) = 0);

    IF V_ACTIVE_COUNT = 0 THEN
      UPDATE BOX_TRANSFORMER
      SET STATUS = 0,
          UPDATED_AT = LOCALTIMESTAMP
      WHERE ID = V_TRANSFORMER_ID
        AND IS_DELETED = 0
        AND STATUS = 1;
    END IF;
  END IF;
END;
/

COMMIT;
