/*
  PSM-Smart Oracle 21c mock data script.

  Scope:
  - Demo/runtime data for local development, UI preview, and workflow testing.
  - Includes 1-second sampled points, one serious alarm, one generated
    maintenance task, and cabinet door event logs.
*/

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_VOLTAGE_AB'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_VOLTAGE_AB'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_VOLTAGE_AB'),
  TIMESTAMP '2026-05-06 10:00:00',
  10.1200,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_CURRENT_A'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_CURRENT_A'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_CURRENT_A'),
  TIMESTAMP '2026-05-06 10:00:00',
  386.4000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_POWER_FACTOR'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_POWER_FACTOR'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'IN01_POWER_FACTOR'),
  TIMESTAMP '2026-05-06 10:00:00',
  0.9300,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_VOLTAGE'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_VOLTAGE'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_VOLTAGE'),
  TIMESTAMP '2026-05-06 10:00:00',
  401.2000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  TIMESTAMP '2026-05-06 10:00:00',
  0.9100,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'BOX_OIL_TEMP'),
  NULL,
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'BOX_OIL_TEMP'),
  TIMESTAMP '2026-05-06 10:00:00',
  62.8000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_TEMP'),
  NULL,
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_TEMP'),
  TIMESTAMP '2026-05-06 10:00:00',
  32.6000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  TIMESTAMP '2026-05-06 10:00:01',
  0.8800,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  TIMESTAMP '2026-05-06 10:00:02',
  0.7800,
  1,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'BOX_OIL_TEMP'),
  NULL,
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'BOX_OIL_TEMP'),
  TIMESTAMP '2026-05-06 10:00:02',
  64.1000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_ID, SAMPLE_TIME, VAL, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_DOOR_STATUS'),
  NULL,
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_DOOR_STATUS'),
  TIMESTAMP '2026-05-06 10:00:02',
  1.0000,
  0,
  LOCALTIMESTAMP
);

INSERT INTO ALARM_LOG (
  ID,
  TRANSFORMER_ID,
  CIRCUIT_ID,
  POINT_ID,
  ALARM_TYPE,
  ALARM_LEVEL,
  START_TIME,
  END_TIME,
  START_VAL,
  END_VAL,
  STATUS,
  CREATED_AT
)
VALUES (
  SEQ_ALARM_LOG.NEXTVAL,
  (SELECT TRANSFORMER_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT CIRCUIT_ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'OUT01_POWER_FACTOR'),
  'POWER_FACTOR_LOW',
  'SERIOUS',
  TIMESTAMP '2026-05-06 10:00:02',
  NULL,
  0.7800,
  0.7800,
  0,
  LOCALTIMESTAMP
);

INSERT INTO MAINT_TASK (
  TASK_ID,
  ALARM_ID,
  STATUS,
  ASSIGNEE,
  FEEDBACK,
  CREATED_AT,
  UPDATED_AT,
  FINISHED_AT
)
VALUES (
  SEQ_MAINT_TASK.NEXTVAL,
  (SELECT ID FROM ALARM_LOG WHERE ALARM_TYPE = 'POWER_FACTOR_LOW' AND START_TIME = TIMESTAMP '2026-05-06 10:00:02'),
  0,
  'engineer01',
  NULL,
  LOCALTIMESTAMP,
  NULL,
  NULL
);

INSERT INTO CABINET_DOOR_LOG (
  ID,
  TRANSFORMER_ID,
  POINT_ID,
  EVENT_TYPE,
  EVENT_TIME,
  DOOR_STATUS,
  NOTE,
  CREATED_AT
)
VALUES (
  SEQ_CABINET_DOOR_LOG.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_DOOR_STATUS'),
  'OPEN',
  TIMESTAMP '2026-05-06 09:59:50',
  1,
  'Routine cabinet inspection started.',
  LOCALTIMESTAMP
);

INSERT INTO CABINET_DOOR_LOG (
  ID,
  TRANSFORMER_ID,
  POINT_ID,
  EVENT_TYPE,
  EVENT_TIME,
  DOOR_STATUS,
  NOTE,
  CREATED_AT
)
VALUES (
  SEQ_CABINET_DOOR_LOG.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM MEASURE_POINT WHERE POINT_CODE = 'CABINET_DOOR_STATUS'),
  'CLOSE',
  TIMESTAMP '2026-05-06 10:01:10',
  0,
  'Routine cabinet inspection finished.',
  LOCALTIMESTAMP
);

COMMIT;
