/*
  PSM-Smart Oracle 21c mock data script.

  Scope:
  - Demo/runtime data for local development, UI preview, and workflow testing.
  - Includes sampled time-series points, one serious alarm, and one generated
    maintenance task.

  TODO:
  - Current rows are placeholder demo data.
  - After the Java acquisition engine is implemented, replace or generate this
    file from realistic Normal/Burst simulation output.
*/

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_LOAD_CURRENT'),
  TIMESTAMP '2026-05-06 09:55:00',
  512.3000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_LOAD_CURRENT'),
  TIMESTAMP '2026-05-06 09:56:00',
  518.7000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_LOAD_CURRENT'),
  TIMESTAMP '2026-05-06 09:57:00',
  526.2000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_OIL_TEMP'),
  TIMESTAMP '2026-05-06 09:55:00',
  63.1000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_OIL_TEMP'),
  TIMESTAMP '2026-05-06 09:56:00',
  63.4000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:55:00',
  72.0000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:56:00',
  72.4000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '10kV I段母线'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'BUS1_VOLTAGE'),
  TIMESTAMP '2026-05-06 09:55:00',
  10.3200,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '10kV I段母线'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'BUS1_AMBIENT_TEMP'),
  TIMESTAMP '2026-05-06 09:55:00',
  32.6000,
  0,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:59:56',
  76.8000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:59:57',
  78.2000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:59:58',
  81.9000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 09:59:59',
  86.7000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:00',
  92.5000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:01',
  93.6000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:02',
  94.1000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:03',
  93.8000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:04',
  92.9000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO TS_RAW_DATA (ID, DEVICE_ID, TAG_ID, SAMPLE_TIME, VAL, FREQ_FLAG, QUALITY_FLAG, CREATED_AT)
VALUES (
  SEQ_TS_RAW_DATA.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  TIMESTAMP '2026-05-06 10:00:05',
  91.7000,
  1,
  0,
  SYSTIMESTAMP
);

INSERT INTO ALARM_LOG (
  ID,
  DEVICE_ID,
  TAG_ID,
  ALARM_TYPE,
  ALARM_LEVEL,
  START_TIME,
  END_TIME,
  START_VAL,
  END_VAL,
  STATUS,
  CREATED_AT
)
VALUES (
  SEQ_ALARM_LOG.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  (SELECT ID FROM TAG_BASE WHERE TAG_CODE = 'TR1_WINDING_TEMP'),
  'TEMP_RATE',
  'SERIOUS',
  TIMESTAMP '2026-05-06 10:00:00',
  NULL,
  76.8000,
  92.5000,
  0,
  SYSTIMESTAMP
);

INSERT INTO MAINT_TASK (
  TASK_ID,
  ALARM_ID,
  STATUS,
  ASSIGNEE,
  FEEDBACK,
  CREATED_AT,
  UPDATED_AT,
  FINISHED_AT
)
VALUES (
  SEQ_MAINT_TASK.NEXTVAL,
  (SELECT ID FROM ALARM_LOG WHERE ALARM_TYPE = 'TEMP_RATE' AND START_TIME = TIMESTAMP '2026-05-06 10:00:00'),
  0,
  '张维保',
  NULL,
  SYSTIMESTAMP,
  NULL,
  NULL
);

COMMIT;

