/*
  PSM-Smart Oracle 21c schema script.

  Rebuilds the local demo schema for box-type transformer monitoring.
*/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAINT_TASK CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ALARM_LOG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CABINET_DOOR_LOG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TS_RAW_DATA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MEASURE_POINT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE POWER_CIRCUIT CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BOX_TRANSFORMER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SYS_USER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TAG_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEVICE_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BAY_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STATION_BASE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAINT_PERSON CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAINT_TASK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALARM_LOG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CABINET_DOOR_LOG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TS_RAW_DATA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEASURE_POINT';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_POWER_CIRCUIT';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOX_TRANSFORMER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SYS_USER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TAG_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEVICE_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BAY_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STATION_BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAINT_PERSON';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE TABLE SYS_USER (
  ID NUMBER(19) NOT NULL,
  USERNAME VARCHAR2(64) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  DISPLAY_NAME VARCHAR2(100) NOT NULL,
  ROLE_CODE VARCHAR2(50) NOT NULL,
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  LAST_LOGIN_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_SYS_USER PRIMARY KEY (ID),
  CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_SYS_USER_ROLE CHECK (ROLE_CODE IN ('ADMIN', 'OPERATOR', 'ENGINEER', 'MANAGER')),
  CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE BOX_TRANSFORMER (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_CODE VARCHAR2(64) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  TRANSFORMER_TYPE VARCHAR2(50) DEFAULT 'BOX_TRANSFORMER' NOT NULL,
  RATED_CAPACITY_KVA NUMBER(12, 3),
  RATED_VOLTAGE_RATIO VARCHAR2(50),
  COMMISSION_DATE DATE,
  MANUFACTURER VARCHAR2(100),
  OIL_LEVEL NUMBER(12, 3),
  LOCATION VARCHAR2(200),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_BOX_TRANSFORMER PRIMARY KEY (ID),
  CONSTRAINT UK_BOX_TRANSFORMER_CODE UNIQUE (TRANSFORMER_CODE),
  CONSTRAINT UK_BOX_TRANSFORMER_NAME UNIQUE (NAME),
  CONSTRAINT CK_BOX_TRANSFORMER_TYPE CHECK (TRANSFORMER_TYPE = 'BOX_TRANSFORMER'),
  CONSTRAINT CK_BOX_TRANSFORMER_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE TABLE POWER_CIRCUIT (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  CIRCUIT_CODE VARCHAR2(64) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DIRECTION VARCHAR2(20) NOT NULL,
  RATED_VOLTAGE_KV NUMBER(12, 3),
  RATED_CURRENT_A NUMBER(12, 3),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_POWER_CIRCUIT PRIMARY KEY (ID),
  CONSTRAINT FK_CIRCUIT_TRANSFORMER FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT UK_CIRCUIT_TRANSFORMER_CODE UNIQUE (TRANSFORMER_ID, CIRCUIT_CODE),
  CONSTRAINT CK_CIRCUIT_DIRECTION CHECK (DIRECTION IN ('INCOMING', 'OUTGOING')),
  CONSTRAINT CK_POWER_CIRCUIT_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE TABLE MEASURE_POINT (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  CIRCUIT_ID NUMBER(19),
  POINT_CODE VARCHAR2(64) NOT NULL,
  POINT_NAME VARCHAR2(100) NOT NULL,
  POINT_GROUP VARCHAR2(50) NOT NULL,
  MEASURE_TYPE VARCHAR2(50) NOT NULL,
  PHASE_CODE VARCHAR2(20) DEFAULT 'NONE' NOT NULL,
  UNIT VARCHAR2(20),
  MIN_LIMIT NUMBER(14, 4),
  MAX_LIMIT NUMBER(14, 4),
  RATE_LIMIT NUMBER(14, 4),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_MEASURE_POINT PRIMARY KEY (ID),
  CONSTRAINT FK_POINT_TRANSFORMER FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT FK_POINT_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES POWER_CIRCUIT (ID),
  CONSTRAINT UK_POINT_TRANSFORMER_CODE UNIQUE (TRANSFORMER_ID, POINT_CODE),
  CONSTRAINT CK_POINT_GROUP CHECK (POINT_GROUP IN ('ELECTRIC_IN', 'ELECTRIC_OUT', 'TRANSFORMER', 'CABINET')),
  CONSTRAINT CK_POINT_MEASURE_TYPE CHECK (MEASURE_TYPE IN (
    'VOLTAGE',
    'CURRENT',
    'POWER_FACTOR',
    'ENERGY',
    'OIL_TEMP',
    'SWITCH_STATUS',
    'FUSE_STATUS',
    'CABINET_TEMP',
    'CABINET_HUMIDITY',
    'SMOKE_STATUS',
    'DOOR_STATUS',
    'FREQUENCY'
  )),
  CONSTRAINT CK_POINT_PHASE CHECK (PHASE_CODE IN ('A', 'B', 'C', 'AB', 'BC', 'CA', 'TOTAL', 'NONE')),
  CONSTRAINT CK_MEASURE_POINT_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE TS_RAW_DATA (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  CIRCUIT_ID NUMBER(19),
  POINT_ID NUMBER(19) NOT NULL,
  SAMPLE_TIME TIMESTAMP NOT NULL,
  VAL NUMBER(14, 4) NOT NULL,
  QUALITY_FLAG NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_TS_RAW_DATA PRIMARY KEY (ID),
  CONSTRAINT FK_TS_TRANSFORMER FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT FK_TS_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES POWER_CIRCUIT (ID),
  CONSTRAINT FK_TS_POINT FOREIGN KEY (POINT_ID) REFERENCES MEASURE_POINT (ID),
  CONSTRAINT CK_TS_RAW_QUALITY CHECK (QUALITY_FLAG IN (0, 1, 2))
);

CREATE TABLE CABINET_DOOR_LOG (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  POINT_ID NUMBER(19),
  EVENT_TYPE VARCHAR2(30) NOT NULL,
  EVENT_TIME TIMESTAMP NOT NULL,
  DOOR_STATUS NUMBER(1) NOT NULL,
  NOTE VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_CABINET_DOOR_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_DOOR_TRANSFORMER FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT FK_DOOR_POINT FOREIGN KEY (POINT_ID) REFERENCES MEASURE_POINT (ID),
  CONSTRAINT CK_DOOR_EVENT_TYPE CHECK (EVENT_TYPE IN ('OPEN', 'CLOSE', 'FORCED_OPEN', 'ANTI_THEFT')),
  CONSTRAINT CK_DOOR_STATUS CHECK (DOOR_STATUS IN (0, 1))
);

CREATE TABLE ALARM_LOG (
  ID NUMBER(19) NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  CIRCUIT_ID NUMBER(19),
  POINT_ID NUMBER(19),
  ALARM_TYPE VARCHAR2(50) NOT NULL,
  ALARM_LEVEL VARCHAR2(20) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP,
  START_VAL NUMBER(14, 4),
  END_VAL NUMBER(14, 4),
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_ALARM_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_ALARM_TRANSFORMER FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT FK_ALARM_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES POWER_CIRCUIT (ID),
  CONSTRAINT FK_ALARM_POINT FOREIGN KEY (POINT_ID) REFERENCES MEASURE_POINT (ID),
  CONSTRAINT CK_ALARM_LEVEL CHECK (ALARM_LEVEL IN ('WARN', 'SERIOUS')),
  CONSTRAINT CK_ALARM_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE MAINT_TASK (
  TASK_ID NUMBER(19) NOT NULL,
  ALARM_ID NUMBER(19) NOT NULL,
  STATUS NUMBER(2) DEFAULT 0 NOT NULL,
  ASSIGNEE VARCHAR2(100),
  FEEDBACK VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  FINISHED_AT TIMESTAMP,
  CONSTRAINT PK_MAINT_TASK PRIMARY KEY (TASK_ID),
  CONSTRAINT FK_TASK_ALARM FOREIGN KEY (ALARM_ID) REFERENCES ALARM_LOG (ID),
  CONSTRAINT CK_MAINT_TASK_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOX_TRANSFORMER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POWER_CIRCUIT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEASURE_POINT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TS_RAW_DATA START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE SEQ_CABINET_DOOR_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALARM_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAINT_TASK START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_POWER_CIRCUIT_TRANS ON POWER_CIRCUIT (TRANSFORMER_ID);
CREATE INDEX IDX_POINT_TRANSFORMER ON MEASURE_POINT (TRANSFORMER_ID);
CREATE INDEX IDX_POINT_CIRCUIT ON MEASURE_POINT (CIRCUIT_ID);
CREATE INDEX IDX_TS_TRANSFORMER_TIME ON TS_RAW_DATA (TRANSFORMER_ID, SAMPLE_TIME);
CREATE INDEX IDX_TS_CIRCUIT_TIME ON TS_RAW_DATA (CIRCUIT_ID, SAMPLE_TIME);
CREATE INDEX IDX_TS_POINT_TIME ON TS_RAW_DATA (POINT_ID, SAMPLE_TIME);
CREATE INDEX IDX_DOOR_TRANSFORMER_TIME ON CABINET_DOOR_LOG (TRANSFORMER_ID, EVENT_TIME);
CREATE INDEX IDX_ALARM_TRANSFORMER_TIME ON ALARM_LOG (TRANSFORMER_ID, START_TIME);
CREATE INDEX IDX_ALARM_POINT_TIME ON ALARM_LOG (POINT_ID, START_TIME);
CREATE INDEX IDX_TASK_ALARM ON MAINT_TASK (ALARM_ID);
CREATE INDEX IDX_TASK_STATUS ON MAINT_TASK (STATUS, CREATED_AT);
