/*
  PSM-Smart Oracle 21c base data script.

  Initializes one box transformer, one incoming circuit, two outgoing circuits,
  measure points, thresholds, and login users.
*/

INSERT INTO SYS_USER (ID, USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE_CODE, STATUS, LAST_LOGIN_AT, CREATED_AT, UPDATED_AT)
VALUES (SEQ_SYS_USER.NEXTVAL, 'admin', '{noop}admin123', 'System Admin', 'ADMIN', 0, NULL, LOCALTIMESTAMP, NULL);

INSERT INTO SYS_USER (ID, USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE_CODE, STATUS, LAST_LOGIN_AT, CREATED_AT, UPDATED_AT)
VALUES (SEQ_SYS_USER.NEXTVAL, 'operator', '{noop}operator123', 'Operator', 'OPERATOR', 0, NULL, LOCALTIMESTAMP, NULL);

INSERT INTO SYS_USER (ID, USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE_CODE, STATUS, LAST_LOGIN_AT, CREATED_AT, UPDATED_AT)
VALUES (SEQ_SYS_USER.NEXTVAL, 'engineer01', '{noop}engineer123', 'Engineer 01', 'ENGINEER', 0, NULL, LOCALTIMESTAMP, NULL);

INSERT INTO SYS_USER (ID, USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE_CODE, STATUS, LAST_LOGIN_AT, CREATED_AT, UPDATED_AT)
VALUES (SEQ_SYS_USER.NEXTVAL, 'manager', '{noop}manager123', 'Maintenance Manager', 'MANAGER', 0, NULL, LOCALTIMESTAMP, NULL);

INSERT INTO BOX_TRANSFORMER (
  ID, TRANSFORMER_CODE, NAME, TRANSFORMER_TYPE, RATED_CAPACITY_KVA,
  RATED_VOLTAGE_RATIO, COMMISSION_DATE, MANUFACTURER, OIL_LEVEL,
  LOCATION, STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_BOX_TRANSFORMER.NEXTVAL, 'BOX-TR-001', 'East Park Box Transformer 1',
  'BOX_TRANSFORMER', 800.000, '10/0.4kV', DATE '2024-06-18',
  'East Electric Equipment Co Ltd', 92.500, 'East Industrial Park Zone A',
  1, LOCALTIMESTAMP, NULL
);

INSERT INTO POWER_CIRCUIT (
  ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION, RATED_VOLTAGE_KV,
  RATED_CURRENT_A, STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_POWER_CIRCUIT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  'IN01', '10kV Incoming', 'INCOMING', 10.000, 630.000, 0, LOCALTIMESTAMP, NULL
);

INSERT INTO POWER_CIRCUIT (
  ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION, RATED_VOLTAGE_KV,
  RATED_CURRENT_A, STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_POWER_CIRCUIT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  'OUT01', '0.4kV Outgoing 1', 'OUTGOING', 0.400, 250.000, 0, LOCALTIMESTAMP, NULL
);

INSERT INTO POWER_CIRCUIT (
  ID, TRANSFORMER_ID, CIRCUIT_CODE, NAME, DIRECTION, RATED_VOLTAGE_KV,
  RATED_CURRENT_A, STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_POWER_CIRCUIT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  'OUT02', '0.4kV Outgoing 2', 'OUTGOING', 0.400, 180.000, 0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'IN01'),
  'IN01_VOLTAGE_AB', 'Incoming AB Voltage', 'ELECTRIC_IN',
  'VOLTAGE', 'AB', 'kV', 9.5000, 10.8000, 0.5000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'IN01'),
  'IN01_CURRENT_A', 'Incoming A Current', 'ELECTRIC_IN',
  'CURRENT', 'A', 'A', 0.0000, 630.0000, 80.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'IN01'),
  'IN01_POWER_FACTOR', 'Incoming Power Factor', 'ELECTRIC_IN',
  'POWER_FACTOR', 'TOTAL', 'PF', 0.8500, 1.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'IN01'),
  'IN01_ENERGY', 'Incoming Energy', 'ELECTRIC_IN',
  'ENERGY', 'TOTAL', 'kWh', 0.0000, NULL, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'IN01'),
  'IN01_FREQUENCY', 'Incoming Frequency', 'ELECTRIC_IN',
  'FREQUENCY', 'TOTAL', 'Hz', 49.5000, 50.5000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT01'),
  'OUT01_VOLTAGE', 'Outgoing 1 Voltage', 'ELECTRIC_OUT',
  'VOLTAGE', 'TOTAL', 'V', 350.0000, 430.0000, 20.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT01'),
  'OUT01_CURRENT', 'Outgoing 1 Current', 'ELECTRIC_OUT',
  'CURRENT', 'TOTAL', 'A', 0.0000, 250.0000, 40.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT01'),
  'OUT01_POWER_FACTOR', 'Outgoing 1 Power Factor', 'ELECTRIC_OUT',
  'POWER_FACTOR', 'TOTAL', 'PF', 0.8500, 1.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT01'),
  'OUT01_ENERGY', 'Outgoing 1 Energy', 'ELECTRIC_OUT',
  'ENERGY', 'TOTAL', 'kWh', 0.0000, NULL, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT02'),
  'OUT02_VOLTAGE', 'Outgoing 2 Voltage', 'ELECTRIC_OUT',
  'VOLTAGE', 'TOTAL', 'V', 350.0000, 430.0000, 20.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT02'),
  'OUT02_CURRENT', 'Outgoing 2 Current', 'ELECTRIC_OUT',
  'CURRENT', 'TOTAL', 'A', 0.0000, 180.0000, 35.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT02'),
  'OUT02_POWER_FACTOR', 'Outgoing 2 Power Factor', 'ELECTRIC_OUT',
  'POWER_FACTOR', 'TOTAL', 'PF', 0.8500, 1.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  (SELECT ID FROM POWER_CIRCUIT WHERE CIRCUIT_CODE = 'OUT02'),
  'OUT02_ENERGY', 'Outgoing 2 Energy', 'ELECTRIC_OUT',
  'ENERGY', 'TOTAL', 'kWh', 0.0000, NULL, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'BOX_OIL_TEMP', 'Transformer Oil Temperature', 'TRANSFORMER',
  'OIL_TEMP', 'NONE', 'C', -20.0000, 85.0000, 5.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'BOX_SWITCH_STATUS', 'Switch Closed Status', 'TRANSFORMER',
  'SWITCH_STATUS', 'NONE', NULL, 0.0000, 1.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'BOX_FUSE_STATUS', 'Fuse Status', 'TRANSFORMER',
  'FUSE_STATUS', 'NONE', NULL, 0.0000, 0.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'CABINET_TEMP', 'Cabinet Temperature', 'CABINET',
  'CABINET_TEMP', 'NONE', 'C', -20.0000, 45.0000, 3.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'CABINET_HUMIDITY', 'Cabinet Humidity', 'CABINET',
  'CABINET_HUMIDITY', 'NONE', '%', 0.0000, 80.0000, 8.0000,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'CABINET_SMOKE_STATUS', 'Smoke Sensor Status', 'CABINET',
  'SMOKE_STATUS', 'NONE', NULL, 0.0000, 0.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

INSERT INTO MEASURE_POINT (
  ID, TRANSFORMER_ID, CIRCUIT_ID, POINT_CODE, POINT_NAME, POINT_GROUP,
  MEASURE_TYPE, PHASE_CODE, UNIT, MIN_LIMIT, MAX_LIMIT, RATE_LIMIT,
  STATUS, CREATED_AT, UPDATED_AT
)
VALUES (
  SEQ_MEASURE_POINT.NEXTVAL,
  (SELECT ID FROM BOX_TRANSFORMER WHERE TRANSFORMER_CODE = 'BOX-TR-001'),
  NULL, 'CABINET_DOOR_STATUS', 'Cabinet Door Status', 'CABINET',
  'DOOR_STATUS', 'NONE', NULL, 0.0000, 1.0000, NULL,
  0, LOCALTIMESTAMP, NULL
);

COMMIT;
