/*
  PSM-Smart Oracle 21c Data Pump backup extension.

  Replaces the previous in-schema DATA_SNAPSHOT_* copy tables with table-mode
  DBMS_DATAPUMP jobs. Only business table rows are exported/imported.
*/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_BACKUP';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_DATA_SNAPSHOT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DATA_SNAPSHOT START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'DATA_SNAPSHOT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DATA_SNAPSHOT (
        ID NUMBER(19) NOT NULL,
        SNAPSHOT_NAME VARCHAR2(100) NOT NULL,
        NOTE VARCHAR2(500),
        DUMP_FILE_NAME VARCHAR2(255),
        LOG_FILE_NAME VARCHAR2(255),
        RESTORE_LOG_FILE_NAME VARCHAR2(255),
        STATUS VARCHAR2(30) DEFAULT 'FAILED' NOT NULL,
        TRANSFORMER_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        CIRCUIT_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        POINT_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        RAW_DATA_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        ARCHIVE_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        DOOR_LOG_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        ALARM_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        TASK_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
        CREATED_BY VARCHAR2(64),
        CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
        RESTORED_BY VARCHAR2(64),
        RESTORED_AT TIMESTAMP,
        ERROR_MESSAGE VARCHAR2(2000),
        CONSTRAINT PK_DATA_SNAPSHOT PRIMARY KEY (ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  PROCEDURE ADD_COLUMN(P_COLUMN_NAME IN VARCHAR2, P_DEFINITION IN VARCHAR2) IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'DATA_SNAPSHOT'
      AND COLUMN_NAME = P_COLUMN_NAME;

    IF V_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE DATA_SNAPSHOT ADD (' || P_DEFINITION || ')';
    END IF;
  END ADD_COLUMN;
BEGIN
  ADD_COLUMN('DUMP_FILE_NAME', 'DUMP_FILE_NAME VARCHAR2(255)');
  ADD_COLUMN('LOG_FILE_NAME', 'LOG_FILE_NAME VARCHAR2(255)');
  ADD_COLUMN('RESTORE_LOG_FILE_NAME', 'RESTORE_LOG_FILE_NAME VARCHAR2(255)');
  ADD_COLUMN('STATUS', 'STATUS VARCHAR2(30) DEFAULT ''FAILED'' NOT NULL');
  ADD_COLUMN('ARCHIVE_COUNT', 'ARCHIVE_COUNT NUMBER(19) DEFAULT 0 NOT NULL');
  ADD_COLUMN('DOOR_LOG_COUNT', 'DOOR_LOG_COUNT NUMBER(19) DEFAULT 0 NOT NULL');
  ADD_COLUMN('ERROR_MESSAGE', 'ERROR_MESSAGE VARCHAR2(2000)');
END;
/

UPDATE DATA_SNAPSHOT
SET ERROR_MESSAGE = NVL(ERROR_MESSAGE, 'Legacy in-schema snapshot cannot be restored by Data Pump.')
WHERE DUMP_FILE_NAME IS NULL
  AND STATUS = 'FAILED'
  AND ERROR_MESSAGE IS NULL;

COMMIT;

DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(1)
  INTO V_COUNT
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'CK_DATA_SNAPSHOT_STATUS';

  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE DATA_SNAPSHOT ADD CONSTRAINT CK_DATA_SNAPSHOT_STATUS
      CHECK (STATUS IN ('CREATING', 'SUCCESS', 'FAILED', 'RESTORING', 'RESTORE_FAILED'))
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_TASK CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_ALARM CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_DOOR_LOG CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_DAY_ARCHIVE CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_RAW_DATA CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_POINT CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_CIRCUIT CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DATA_SNAPSHOT_TRANSFORMER CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE PACKAGE PKG_PSM_BACKUP AS
  PROCEDURE CREATE_BACKUP(
      P_BACKUP_NAME IN VARCHAR2,
      P_NOTE        IN VARCHAR2,
      P_ACTOR       IN VARCHAR2,
      P_BACKUP_ID   OUT NUMBER
  );

  PROCEDURE RESTORE_BACKUP(
      P_BACKUP_ID IN NUMBER,
      P_ACTOR     IN VARCHAR2
  );
END PKG_PSM_BACKUP;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_BACKUP AS
  C_DIRECTORY_NAME CONSTANT VARCHAR2(30) := 'PSM_BACKUP_DIR';
  C_TABLE_NAME_EXPR CONSTANT VARCHAR2(1000) := q'[IN ('BOX_TRANSFORMER','POWER_CIRCUIT','MEASURE_POINT','TS_RAW_DATA','TS_RAW_DATA_DAY_ARCHIVE','CABINET_DOOR_LOG','ALARM_LOG','MAINT_TASK')]';

  FUNCTION NORMALIZE_TEXT(P_TEXT IN VARCHAR2, P_LIMIT IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN SUBSTR(NULLIF(TRIM(P_TEXT), ''), 1, P_LIMIT);
  END NORMALIZE_TEXT;

  FUNCTION FILE_STAMP RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3');
  END FILE_STAMP;

  FUNCTION CURRENT_SCHEMA_NAME RETURN VARCHAR2 IS
  BEGIN
    RETURN SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
  END CURRENT_SCHEMA_NAME;

  FUNCTION ERROR_DETAIL RETURN VARCHAR2 IS
  BEGIN
    RETURN SUBSTR(SQLERRM || CHR(10) || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 1, 2000);
  END ERROR_DETAIL;

  PROCEDURE COUNT_BUSINESS_ROWS(
      P_TRANSFORMER_COUNT OUT NUMBER,
      P_CIRCUIT_COUNT     OUT NUMBER,
      P_POINT_COUNT       OUT NUMBER,
      P_RAW_DATA_COUNT    OUT NUMBER,
      P_ARCHIVE_COUNT     OUT NUMBER,
      P_DOOR_LOG_COUNT    OUT NUMBER,
      P_ALARM_COUNT       OUT NUMBER,
      P_TASK_COUNT        OUT NUMBER
  ) IS
  BEGIN
    SELECT COUNT(1) INTO P_TRANSFORMER_COUNT FROM BOX_TRANSFORMER;
    SELECT COUNT(1) INTO P_CIRCUIT_COUNT FROM POWER_CIRCUIT;
    SELECT COUNT(1) INTO P_POINT_COUNT FROM MEASURE_POINT;
    SELECT COUNT(1) INTO P_RAW_DATA_COUNT FROM TS_RAW_DATA;
    SELECT COUNT(1) INTO P_ARCHIVE_COUNT FROM TS_RAW_DATA_DAY_ARCHIVE;
    SELECT COUNT(1) INTO P_DOOR_LOG_COUNT FROM CABINET_DOOR_LOG;
    SELECT COUNT(1) INTO P_ALARM_COUNT FROM ALARM_LOG;
    SELECT COUNT(1) INTO P_TASK_COUNT FROM MAINT_TASK;
  END COUNT_BUSINESS_ROWS;

  PROCEDURE BUMP_SEQUENCE(P_SEQUENCE_NAME IN VARCHAR2, P_MIN_NEXT_VALUE IN NUMBER) IS
    V_CURRENT_VALUE NUMBER;
    V_INCREMENT NUMBER;
  BEGIN
    IF P_MIN_NEXT_VALUE IS NULL OR P_MIN_NEXT_VALUE <= 1 THEN
      RETURN;
    END IF;

    EXECUTE IMMEDIATE 'SELECT ' || P_SEQUENCE_NAME || '.NEXTVAL FROM DUAL' INTO V_CURRENT_VALUE;
    IF V_CURRENT_VALUE < P_MIN_NEXT_VALUE THEN
      V_INCREMENT := P_MIN_NEXT_VALUE - V_CURRENT_VALUE;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY ' || V_INCREMENT;
      EXECUTE IMMEDIATE 'SELECT ' || P_SEQUENCE_NAME || '.NEXTVAL FROM DUAL' INTO V_CURRENT_VALUE;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY 1';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || P_SEQUENCE_NAME || ' INCREMENT BY 1';
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
      RAISE;
  END BUMP_SEQUENCE;

  PROCEDURE BUMP_ALL_SEQUENCES IS
    V_MIN_NEXT_VALUE NUMBER;
  BEGIN
    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM BOX_TRANSFORMER;
    BUMP_SEQUENCE('SEQ_BOX_TRANSFORMER', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM POWER_CIRCUIT;
    BUMP_SEQUENCE('SEQ_POWER_CIRCUIT', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM MEASURE_POINT;
    BUMP_SEQUENCE('SEQ_MEASURE_POINT', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM TS_RAW_DATA;
    BUMP_SEQUENCE('SEQ_TS_RAW_DATA', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM TS_RAW_DATA_DAY_ARCHIVE;
    BUMP_SEQUENCE('SEQ_TS_RAW_DATA_DAY_ARCHIVE', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM CABINET_DOOR_LOG;
    BUMP_SEQUENCE('SEQ_CABINET_DOOR_LOG', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM ALARM_LOG;
    BUMP_SEQUENCE('SEQ_ALARM_LOG', V_MIN_NEXT_VALUE);

    SELECT NVL(MAX(TASK_ID), 0) + 1 INTO V_MIN_NEXT_VALUE FROM MAINT_TASK;
    BUMP_SEQUENCE('SEQ_MAINT_TASK', V_MIN_NEXT_VALUE);
  END BUMP_ALL_SEQUENCES;

  PROCEDURE REFRESH_SIM_CONTROL IS
    V_LAST_WRITE_AT TIMESTAMP;
    V_WRITE_COUNT NUMBER;
    V_ALARM_COUNT NUMBER;
    V_TASK_COUNT NUMBER;
  BEGIN
    SELECT MAX(SAMPLE_TIME), COUNT(1)
    INTO V_LAST_WRITE_AT, V_WRITE_COUNT
    FROM TS_RAW_DATA;

    SELECT COUNT(1) INTO V_ALARM_COUNT FROM ALARM_LOG;
    SELECT COUNT(1) INTO V_TASK_COUNT FROM MAINT_TASK;

    UPDATE SIM_CONTROL
    SET
      RUNNING = 0,
      ANOMALY_ENABLED = 0,
      STARTED_AT = NULL,
      LAST_WRITE_AT = V_LAST_WRITE_AT,
      WRITE_COUNT = V_WRITE_COUNT,
      ALARM_COUNT = V_ALARM_COUNT,
      TASK_COUNT = V_TASK_COUNT,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;

    IF SQL%ROWCOUNT = 0 THEN
      INSERT INTO SIM_CONTROL (
        ID, RUNNING, ANOMALY_ENABLED, STARTED_AT, LAST_WRITE_AT,
        WRITE_COUNT, ALARM_COUNT, TASK_COUNT, NORMAL_INTERVAL_MS,
        ANOMALY_INTERVAL_MS, UPDATED_AT
      )
      VALUES (
        1, 0, 0, NULL, V_LAST_WRITE_AT,
        V_WRITE_COUNT, V_ALARM_COUNT, V_TASK_COUNT, 1000,
        100, LOCALTIMESTAMP
      );
    END IF;
  END REFRESH_SIM_CONTROL;

  PROCEDURE EXECUTE_DDL(P_SQL IN VARCHAR2, P_RAISE_ERRORS IN BOOLEAN) IS
  BEGIN
    EXECUTE IMMEDIATE P_SQL;
  EXCEPTION
    WHEN OTHERS THEN
      IF P_RAISE_ERRORS THEN
        RAISE;
      END IF;
      PKG_PSM_LOG.WRITE_LOG('WARN', 'BACKUP_RESTORE_DDL', SQLERRM, P_SQL);
  END EXECUTE_DDL;

  PROCEDURE SET_RESTORE_OBJECTS(P_ENABLED IN BOOLEAN, P_RAISE_ERRORS IN BOOLEAN) IS
    V_CONSTRAINT_ACTION VARCHAR2(32);
    V_TRIGGER_ACTION VARCHAR2(16);
  BEGIN
    IF P_ENABLED THEN
      V_CONSTRAINT_ACTION := ' ENABLE CONSTRAINT ';
      V_TRIGGER_ACTION := ' ENABLE';
    ELSE
      V_CONSTRAINT_ACTION := ' DISABLE CONSTRAINT ';
      V_TRIGGER_ACTION := ' DISABLE';
    END IF;

    FOR R IN (
      SELECT TABLE_NAME, CONSTRAINT_NAME
      FROM USER_CONSTRAINTS
      WHERE CONSTRAINT_TYPE = 'R'
        AND TABLE_NAME IN (
          'POWER_CIRCUIT',
          'MEASURE_POINT',
          'TS_RAW_DATA',
          'TS_RAW_DATA_DAY_ARCHIVE',
          'CABINET_DOOR_LOG',
          'ALARM_LOG',
          'MAINT_TASK'
        )
      ORDER BY TABLE_NAME, CONSTRAINT_NAME
    ) LOOP
      EXECUTE_DDL(
        'ALTER TABLE ' || R.TABLE_NAME || V_CONSTRAINT_ACTION || R.CONSTRAINT_NAME,
        P_RAISE_ERRORS
      );
    END LOOP;

    FOR R IN (
      SELECT TRIGGER_NAME
      FROM USER_TRIGGERS
      WHERE TRIGGER_NAME IN ('TRG_PSM_ALARM_OPEN_STATUS', 'TRG_PSM_TASK_COMPLETE_STATUS')
      ORDER BY TRIGGER_NAME
    ) LOOP
      EXECUTE_DDL('ALTER TRIGGER ' || R.TRIGGER_NAME || V_TRIGGER_ACTION, P_RAISE_ERRORS);
    END LOOP;
  END SET_RESTORE_OBJECTS;

  PROCEDURE TRUNCATE_BUSINESS_TABLES IS
  BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE MAINT_TASK';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ALARM_LOG';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CABINET_DOOR_LOG';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TS_RAW_DATA';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE TS_RAW_DATA_DAY_ARCHIVE';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE MEASURE_POINT';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE POWER_CIRCUIT';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE BOX_TRANSFORMER';
  END TRUNCATE_BUSINESS_TABLES;

  PROCEDURE APPLY_TABLE_FILTER(P_HANDLE IN NUMBER) IS
    V_SCHEMA_EXPR VARCHAR2(261);
  BEGIN
    V_SCHEMA_EXPR := '= ''' || REPLACE(CURRENT_SCHEMA_NAME, '''', '''''') || '''';
    DBMS_DATAPUMP.METADATA_FILTER(P_HANDLE, 'SCHEMA_EXPR', V_SCHEMA_EXPR);
    DBMS_DATAPUMP.METADATA_FILTER(P_HANDLE, 'NAME_EXPR', C_TABLE_NAME_EXPR, 'TABLE');
  END APPLY_TABLE_FILTER;

  PROCEDURE RUN_EXPORT(
      P_DUMP_FILE IN VARCHAR2,
      P_LOG_FILE  IN VARCHAR2,
      P_JOB_NAME  IN VARCHAR2,
      P_JOB_STATE OUT VARCHAR2
  ) IS
    V_HANDLE NUMBER;
  BEGIN
    V_HANDLE := DBMS_DATAPUMP.OPEN(
      operation => 'EXPORT',
      job_mode => 'TABLE',
      remote_link => NULL,
      job_name => P_JOB_NAME,
      version => 'COMPATIBLE'
    );

    DBMS_DATAPUMP.ADD_FILE(
      handle => V_HANDLE,
      filename => P_DUMP_FILE,
      directory => C_DIRECTORY_NAME,
      filetype => DBMS_DATAPUMP.KU$_FILE_TYPE_DUMP_FILE,
      reusefile => 1
    );
    DBMS_DATAPUMP.ADD_FILE(
      handle => V_HANDLE,
      filename => P_LOG_FILE,
      directory => C_DIRECTORY_NAME,
      filetype => DBMS_DATAPUMP.KU$_FILE_TYPE_LOG_FILE,
      reusefile => 1
    );
    DBMS_DATAPUMP.SET_PARAMETER(V_HANDLE, 'CONTENT', 'DATA_ONLY');
    APPLY_TABLE_FILTER(V_HANDLE);
    DBMS_DATAPUMP.START_JOB(V_HANDLE);
    DBMS_DATAPUMP.WAIT_FOR_JOB(V_HANDLE, P_JOB_STATE);
    V_HANDLE := NULL;

    IF NVL(P_JOB_STATE, 'UNKNOWN') != 'COMPLETED' THEN
      RAISE_APPLICATION_ERROR(-20621, 'Data Pump export ended with state ' || NVL(P_JOB_STATE, 'UNKNOWN'));
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      IF V_HANDLE IS NOT NULL THEN
        BEGIN
          DBMS_DATAPUMP.DETACH(V_HANDLE);
        EXCEPTION
          WHEN OTHERS THEN NULL;
        END;
      END IF;
      RAISE;
  END RUN_EXPORT;

  PROCEDURE RUN_IMPORT(
      P_DUMP_FILE IN VARCHAR2,
      P_LOG_FILE  IN VARCHAR2,
      P_JOB_NAME  IN VARCHAR2,
      P_JOB_STATE OUT VARCHAR2
  ) IS
    V_HANDLE NUMBER;
  BEGIN
    V_HANDLE := DBMS_DATAPUMP.OPEN(
      operation => 'IMPORT',
      job_mode => 'TABLE',
      remote_link => NULL,
      job_name => P_JOB_NAME,
      version => 'COMPATIBLE'
    );

    DBMS_DATAPUMP.ADD_FILE(
      handle => V_HANDLE,
      filename => P_DUMP_FILE,
      directory => C_DIRECTORY_NAME,
      filetype => DBMS_DATAPUMP.KU$_FILE_TYPE_DUMP_FILE
    );
    DBMS_DATAPUMP.ADD_FILE(
      handle => V_HANDLE,
      filename => P_LOG_FILE,
      directory => C_DIRECTORY_NAME,
      filetype => DBMS_DATAPUMP.KU$_FILE_TYPE_LOG_FILE,
      reusefile => 1
    );
    DBMS_DATAPUMP.SET_PARAMETER(V_HANDLE, 'CONTENT', 'DATA_ONLY');
    DBMS_DATAPUMP.SET_PARAMETER(V_HANDLE, 'TABLE_EXISTS_ACTION', 'APPEND');
    APPLY_TABLE_FILTER(V_HANDLE);
    DBMS_DATAPUMP.START_JOB(V_HANDLE);
    DBMS_DATAPUMP.WAIT_FOR_JOB(V_HANDLE, P_JOB_STATE);
    V_HANDLE := NULL;

    IF NVL(P_JOB_STATE, 'UNKNOWN') != 'COMPLETED' THEN
      RAISE_APPLICATION_ERROR(-20622, 'Data Pump import ended with state ' || NVL(P_JOB_STATE, 'UNKNOWN'));
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      IF V_HANDLE IS NOT NULL THEN
        BEGIN
          DBMS_DATAPUMP.DETACH(V_HANDLE);
        EXCEPTION
          WHEN OTHERS THEN NULL;
        END;
      END IF;
      RAISE;
  END RUN_IMPORT;

  PROCEDURE ASSERT_RESTORABLE_BACKUP(
      P_BACKUP_ID IN NUMBER,
      P_DUMP_FILE OUT VARCHAR2
  ) IS
    V_STATUS VARCHAR2(30);
  BEGIN
    SELECT DUMP_FILE_NAME, STATUS
    INTO P_DUMP_FILE, V_STATUS
    FROM DATA_SNAPSHOT
    WHERE ID = P_BACKUP_ID;

    IF P_DUMP_FILE IS NULL OR V_STATUS NOT IN ('SUCCESS', 'RESTORE_FAILED') THEN
      RAISE_APPLICATION_ERROR(-20600, 'Backup dump file is not available for restore.');
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20600, 'Backup does not exist.');
  END ASSERT_RESTORABLE_BACKUP;

  PROCEDURE CREATE_BACKUP(
      P_BACKUP_NAME IN VARCHAR2,
      P_NOTE        IN VARCHAR2,
      P_ACTOR       IN VARCHAR2,
      P_BACKUP_ID   OUT NUMBER
  ) IS
    V_NAME VARCHAR2(100) := NVL(NORMALIZE_TEXT(P_BACKUP_NAME, 100), 'backup-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));
    V_NOTE VARCHAR2(500) := NORMALIZE_TEXT(P_NOTE, 500);
    V_ACTOR VARCHAR2(64) := NORMALIZE_TEXT(P_ACTOR, 64);
    V_FILE_PREFIX VARCHAR2(100);
    V_DUMP_FILE VARCHAR2(255);
    V_LOG_FILE VARCHAR2(255);
    V_JOB_NAME VARCHAR2(128);
    V_JOB_STATE VARCHAR2(30);
    V_ERROR VARCHAR2(2000);
    V_TRANSFORMER_COUNT NUMBER := 0;
    V_CIRCUIT_COUNT NUMBER := 0;
    V_POINT_COUNT NUMBER := 0;
    V_RAW_DATA_COUNT NUMBER := 0;
    V_ARCHIVE_COUNT NUMBER := 0;
    V_DOOR_LOG_COUNT NUMBER := 0;
    V_ALARM_COUNT NUMBER := 0;
    V_TASK_COUNT NUMBER := 0;
  BEGIN
    P_BACKUP_ID := SEQ_DATA_SNAPSHOT.NEXTVAL;
    V_FILE_PREFIX := 'psm_backup_' || LPAD(P_BACKUP_ID, 6, '0') || '_' || FILE_STAMP;
    V_DUMP_FILE := V_FILE_PREFIX || '.dmp';
    V_LOG_FILE := V_FILE_PREFIX || '.log';
    V_JOB_NAME := 'PSM_EXP_' || LPAD(MOD(P_BACKUP_ID, 1000000), 6, '0') || '_' || TO_CHAR(SYSDATE, 'HH24MISS');

    COUNT_BUSINESS_ROWS(
      V_TRANSFORMER_COUNT,
      V_CIRCUIT_COUNT,
      V_POINT_COUNT,
      V_RAW_DATA_COUNT,
      V_ARCHIVE_COUNT,
      V_DOOR_LOG_COUNT,
      V_ALARM_COUNT,
      V_TASK_COUNT
    );

    INSERT INTO DATA_SNAPSHOT (
      ID,
      SNAPSHOT_NAME,
      NOTE,
      DUMP_FILE_NAME,
      LOG_FILE_NAME,
      STATUS,
      TRANSFORMER_COUNT,
      CIRCUIT_COUNT,
      POINT_COUNT,
      RAW_DATA_COUNT,
      ARCHIVE_COUNT,
      DOOR_LOG_COUNT,
      ALARM_COUNT,
      TASK_COUNT,
      CREATED_BY,
      CREATED_AT,
      ERROR_MESSAGE
    ) VALUES (
      P_BACKUP_ID,
      V_NAME,
      V_NOTE,
      V_DUMP_FILE,
      V_LOG_FILE,
      'CREATING',
      V_TRANSFORMER_COUNT,
      V_CIRCUIT_COUNT,
      V_POINT_COUNT,
      V_RAW_DATA_COUNT,
      V_ARCHIVE_COUNT,
      V_DOOR_LOG_COUNT,
      V_ALARM_COUNT,
      V_TASK_COUNT,
      V_ACTOR,
      LOCALTIMESTAMP,
      NULL
    );
    COMMIT;

    RUN_EXPORT(V_DUMP_FILE, V_LOG_FILE, V_JOB_NAME, V_JOB_STATE);

    UPDATE DATA_SNAPSHOT
    SET
      STATUS = 'SUCCESS',
      ERROR_MESSAGE = NULL
    WHERE ID = P_BACKUP_ID;

    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'BACKUP_CREATE',
      'Created Data Pump backup ' || P_BACKUP_ID,
      'actor=' || NVL(V_ACTOR, 'unknown') || ' dump=' || V_DUMP_FILE || ' rawRows=' || V_RAW_DATA_COUNT
    );
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := ERROR_DETAIL;
      IF P_BACKUP_ID IS NOT NULL THEN
        UPDATE DATA_SNAPSHOT
        SET
          STATUS = 'FAILED',
          ERROR_MESSAGE = V_ERROR
        WHERE ID = P_BACKUP_ID;
      END IF;

      PKG_PSM_LOG.WRITE_LOG(
        'ERROR',
        'BACKUP_CREATE',
        'Data Pump backup failed ' || NVL(TO_CHAR(P_BACKUP_ID), '-'),
        V_ERROR
      );
      COMMIT;
      RAISE_APPLICATION_ERROR(-20601, 'Data Pump backup failed. Check backup metadata and log file.');
  END CREATE_BACKUP;

  PROCEDURE RESTORE_BACKUP(
      P_BACKUP_ID IN NUMBER,
      P_ACTOR     IN VARCHAR2
  ) IS
    V_ACTOR VARCHAR2(64) := NORMALIZE_TEXT(P_ACTOR, 64);
    V_DUMP_FILE VARCHAR2(255);
    V_RESTORE_LOG_FILE VARCHAR2(255);
    V_JOB_NAME VARCHAR2(128);
    V_JOB_STATE VARCHAR2(30);
    V_ERROR VARCHAR2(2000);
    V_RESTORE_STARTED BOOLEAN := FALSE;
    V_OBJECTS_DISABLED BOOLEAN := FALSE;
  BEGIN
    ASSERT_RESTORABLE_BACKUP(P_BACKUP_ID, V_DUMP_FILE);
    V_RESTORE_LOG_FILE := 'psm_restore_' || LPAD(P_BACKUP_ID, 6, '0') || '_' || FILE_STAMP || '.log';
    V_JOB_NAME := 'PSM_IMP_' || LPAD(MOD(P_BACKUP_ID, 1000000), 6, '0') || '_' || TO_CHAR(SYSDATE, 'HH24MISS');

    UPDATE DATA_SNAPSHOT
    SET
      STATUS = 'RESTORING',
      RESTORE_LOG_FILE_NAME = V_RESTORE_LOG_FILE,
      ERROR_MESSAGE = NULL
    WHERE ID = P_BACKUP_ID;
    COMMIT;

    V_RESTORE_STARTED := TRUE;
    V_OBJECTS_DISABLED := TRUE;
    SET_RESTORE_OBJECTS(FALSE, TRUE);
    TRUNCATE_BUSINESS_TABLES;
    RUN_IMPORT(V_DUMP_FILE, V_RESTORE_LOG_FILE, V_JOB_NAME, V_JOB_STATE);
    SET_RESTORE_OBJECTS(TRUE, TRUE);
    V_OBJECTS_DISABLED := FALSE;
    REFRESH_SIM_CONTROL;
    BUMP_ALL_SEQUENCES;

    UPDATE DATA_SNAPSHOT
    SET
      STATUS = 'SUCCESS',
      RESTORED_BY = V_ACTOR,
      RESTORED_AT = LOCALTIMESTAMP,
      ERROR_MESSAGE = NULL
    WHERE ID = P_BACKUP_ID;

    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'BACKUP_RESTORE',
      'Restored Data Pump backup ' || P_BACKUP_ID,
      'actor=' || NVL(V_ACTOR, 'unknown') || ' dump=' || V_DUMP_FILE
    );
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR := ERROR_DETAIL;

      IF V_RESTORE_STARTED THEN
        IF V_OBJECTS_DISABLED THEN
          SET_RESTORE_OBJECTS(TRUE, FALSE);
        END IF;

        BEGIN
          REFRESH_SIM_CONTROL;
          BUMP_ALL_SEQUENCES;
        EXCEPTION
          WHEN OTHERS THEN
            V_ERROR := SUBSTR(V_ERROR || CHR(10) || 'Post-restore refresh failed: ' || SQLERRM, 1, 2000);
        END;
      END IF;

      IF V_RESTORE_STARTED THEN
        UPDATE DATA_SNAPSHOT
        SET
          STATUS = 'RESTORE_FAILED',
          RESTORE_LOG_FILE_NAME = NVL(V_RESTORE_LOG_FILE, RESTORE_LOG_FILE_NAME),
          ERROR_MESSAGE = V_ERROR
        WHERE ID = P_BACKUP_ID;
      END IF;

      PKG_PSM_LOG.WRITE_LOG(
        'ERROR',
        'BACKUP_RESTORE',
        'Data Pump restore failed ' || NVL(TO_CHAR(P_BACKUP_ID), '-'),
        V_ERROR
      );
      COMMIT;
      RAISE_APPLICATION_ERROR(-20602, 'Data Pump restore failed. Check backup metadata and log file.');
  END RESTORE_BACKUP;
END PKG_PSM_BACKUP;
/

COMMIT;
