/*
  PSM-Smart Oracle 21c base data script.

  Scope:
  - Deployment baseline data required for the system to start with usable
    metadata and login accounts.
  - Includes maintenance people, system users, station/bay/device/tag metadata,
    and threshold parameters.

  This script intentionally does not insert runtime sampling data, alarms, or
  generated maintenance tasks.
*/

INSERT INTO MAINT_PERSON (
  ID,
  PERSON_NAME,
  PHONE,
  EMAIL,
  DEPARTMENT,
  SPECIALTY,
  CERT_NO,
  STATUS,
  CREATED_AT,
  UPDATED_AT
)
VALUES (
  SEQ_MAINT_PERSON.NEXTVAL,
  '张维保',
  '13800000001',
  'zhang.weibao@example.com',
  '变电检修一班',
  '变压器检修',
  'CERT-TR-2026-001',
  0,
  SYSTIMESTAMP,
  NULL
);

INSERT INTO MAINT_PERSON (
  ID,
  PERSON_NAME,
  PHONE,
  EMAIL,
  DEPARTMENT,
  SPECIALTY,
  CERT_NO,
  STATUS,
  CREATED_AT,
  UPDATED_AT
)
VALUES (
  SEQ_MAINT_PERSON.NEXTVAL,
  '李继保',
  '13800000002',
  'li.jibao@example.com',
  '继电保护班',
  '继电保护',
  'CERT-RP-2026-002',
  0,
  SYSTIMESTAMP,
  NULL
);

INSERT INTO SYS_USER (
  ID,
  USERNAME,
  PASSWORD_HASH,
  DISPLAY_NAME,
  ROLE_CODE,
  PERSON_ID,
  STATUS,
  LAST_LOGIN_AT,
  CREATED_AT,
  UPDATED_AT
)
VALUES (
  SEQ_SYS_USER.NEXTVAL,
  'admin',
  '{noop}admin123',
  '系统管理员',
  'ADMIN',
  NULL,
  0,
  NULL,
  SYSTIMESTAMP,
  NULL
);

INSERT INTO SYS_USER (
  ID,
  USERNAME,
  PASSWORD_HASH,
  DISPLAY_NAME,
  ROLE_CODE,
  PERSON_ID,
  STATUS,
  LAST_LOGIN_AT,
  CREATED_AT,
  UPDATED_AT
)
VALUES (
  SEQ_SYS_USER.NEXTVAL,
  'operator',
  '{noop}operator123',
  '运行监控员',
  'OPERATOR',
  NULL,
  0,
  NULL,
  SYSTIMESTAMP,
  NULL
);

INSERT INTO SYS_USER (
  ID,
  USERNAME,
  PASSWORD_HASH,
  DISPLAY_NAME,
  ROLE_CODE,
  PERSON_ID,
  STATUS,
  LAST_LOGIN_AT,
  CREATED_AT,
  UPDATED_AT
)
VALUES (
  SEQ_SYS_USER.NEXTVAL,
  'engineer01',
  '{noop}engineer123',
  '张维保',
  'ENGINEER',
  (SELECT ID FROM MAINT_PERSON WHERE PHONE = '13800000001'),
  0,
  NULL,
  SYSTIMESTAMP,
  NULL
);

INSERT INTO STATION_BASE (ID, NAME, VOLTAGE_LEVEL, LOCATION, CREATED_AT)
VALUES (SEQ_STATION_BASE.NEXTVAL, '城东 110kV 变电站', '110kV', '城东工业园区', SYSTIMESTAMP);

INSERT INTO BAY_BASE (ID, STATION_ID, NAME, BAY_TYPE, CREATED_AT)
VALUES (
  SEQ_BAY_BASE.NEXTVAL,
  (SELECT ID FROM STATION_BASE WHERE NAME = '城东 110kV 变电站'),
  '1号主变间隔',
  'TRANSFORMER',
  SYSTIMESTAMP
);

INSERT INTO BAY_BASE (ID, STATION_ID, NAME, BAY_TYPE, CREATED_AT)
VALUES (
  SEQ_BAY_BASE.NEXTVAL,
  (SELECT ID FROM STATION_BASE WHERE NAME = '城东 110kV 变电站'),
  '10kV 出线间隔',
  'FEEDER',
  SYSTIMESTAMP
);

INSERT INTO DEVICE_BASE (ID, BAY_ID, NAME, DEVICE_TYPE, CURRENT_LIMIT, TEMP_LIMIT, TEMP_RATE_LIMIT, STATUS, CREATED_AT)
VALUES (
  SEQ_DEVICE_BASE.NEXTVAL,
  (SELECT ID FROM BAY_BASE WHERE NAME = '1号主变间隔'),
  '1号主变压器',
  'TRANSFORMER',
  800.000,
  85.000,
  6.000,
  1,
  SYSTIMESTAMP
);

INSERT INTO DEVICE_BASE (ID, BAY_ID, NAME, DEVICE_TYPE, CURRENT_LIMIT, TEMP_LIMIT, TEMP_RATE_LIMIT, STATUS, CREATED_AT)
VALUES (
  SEQ_DEVICE_BASE.NEXTVAL,
  (SELECT ID FROM BAY_BASE WHERE NAME = '10kV 出线间隔'),
  '10kV I段母线',
  'BUS',
  1200.000,
  70.000,
  4.000,
  0,
  SYSTIMESTAMP
);

INSERT INTO TAG_BASE (ID, DEVICE_ID, TAG_CODE, TAG_NAME, UNIT, WARN_LIMIT, RATE_LIMIT, CREATED_AT)
VALUES (
  SEQ_TAG_BASE.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  'TR1_LOAD_CURRENT',
  '负荷电流',
  'A',
  800.000,
  120.000,
  SYSTIMESTAMP
);

INSERT INTO TAG_BASE (ID, DEVICE_ID, TAG_CODE, TAG_NAME, UNIT, WARN_LIMIT, RATE_LIMIT, CREATED_AT)
VALUES (
  SEQ_TAG_BASE.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  'TR1_OIL_TEMP',
  '油温',
  'C',
  85.000,
  5.000,
  SYSTIMESTAMP
);

INSERT INTO TAG_BASE (ID, DEVICE_ID, TAG_CODE, TAG_NAME, UNIT, WARN_LIMIT, RATE_LIMIT, CREATED_AT)
VALUES (
  SEQ_TAG_BASE.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '1号主变压器'),
  'TR1_WINDING_TEMP',
  '绕组温度',
  'C',
  95.000,
  6.000,
  SYSTIMESTAMP
);

INSERT INTO TAG_BASE (ID, DEVICE_ID, TAG_CODE, TAG_NAME, UNIT, WARN_LIMIT, RATE_LIMIT, CREATED_AT)
VALUES (
  SEQ_TAG_BASE.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '10kV I段母线'),
  'BUS1_VOLTAGE',
  '母线电压',
  'kV',
  11.000,
  0.800,
  SYSTIMESTAMP
);

INSERT INTO TAG_BASE (ID, DEVICE_ID, TAG_CODE, TAG_NAME, UNIT, WARN_LIMIT, RATE_LIMIT, CREATED_AT)
VALUES (
  SEQ_TAG_BASE.NEXTVAL,
  (SELECT ID FROM DEVICE_BASE WHERE NAME = '10kV I段母线'),
  'BUS1_AMBIENT_TEMP',
  '环境温度',
  'C',
  45.000,
  3.000,
  SYSTIMESTAMP
);

COMMIT;

