/*
  PSM-Smart Oracle 21c business objects.

  Adds database-driven simulation control, business runtime logs,
  daily archives, and PL/SQL packages for simulation/task/archive logic.
*/

BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_PSM_ARCHIVE_RAW', TRUE);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-27475, -27486, -1031) THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_ARCHIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_TASK';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_SIM';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PSM_LOG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TS_RAW_DATA_DAY_ARCHIVE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DB_RUNTIME_LOG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SIM_CONTROL CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TS_RAW_DATA_DAY_ARCHIVE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DB_RUNTIME_LOG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE TABLE SIM_CONTROL (
  ID NUMBER(1) NOT NULL,
  RUNNING NUMBER(1) DEFAULT 0 NOT NULL,
  ANOMALY_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
  STARTED_AT TIMESTAMP,
  LAST_WRITE_AT TIMESTAMP,
  WRITE_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
  ALARM_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
  TASK_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
  NORMAL_INTERVAL_MS NUMBER(10) DEFAULT 1000 NOT NULL,
  ANOMALY_INTERVAL_MS NUMBER(10) DEFAULT 100 NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_SIM_CONTROL PRIMARY KEY (ID),
  CONSTRAINT CK_SIM_CONTROL_ID CHECK (ID = 1),
  CONSTRAINT CK_SIM_CONTROL_RUNNING CHECK (RUNNING IN (0, 1)),
  CONSTRAINT CK_SIM_CONTROL_ANOMALY CHECK (ANOMALY_ENABLED IN (0, 1))
);

CREATE TABLE DB_RUNTIME_LOG (
  ID NUMBER(19) NOT NULL,
  LEVEL_CODE VARCHAR2(10) NOT NULL,
  EVENT_TYPE VARCHAR2(50) NOT NULL,
  MESSAGE VARCHAR2(500) NOT NULL,
  CONTEXT VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_DB_RUNTIME_LOG PRIMARY KEY (ID),
  CONSTRAINT CK_DB_RUNTIME_LOG_LEVEL CHECK (LEVEL_CODE IN ('DEBUG', 'INFO', 'WARN', 'ERROR'))
);

CREATE TABLE TS_RAW_DATA_DAY_ARCHIVE (
  ID NUMBER(19) NOT NULL,
  ARCHIVE_DAY DATE NOT NULL,
  TRANSFORMER_ID NUMBER(19) NOT NULL,
  CIRCUIT_ID NUMBER(19),
  POINT_ID NUMBER(19) NOT NULL,
  DISPLAY_VAL NUMBER(14, 4) NOT NULL,
  AVG_VAL NUMBER(14, 4),
  MIN_VAL NUMBER(14, 4),
  MAX_VAL NUMBER(14, 4),
  SAMPLE_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
  MAX_QUALITY_FLAG NUMBER(2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  CONSTRAINT PK_TS_RAW_DATA_DAY_ARCHIVE PRIMARY KEY (ID),
  CONSTRAINT UK_TS_DAY_ARCHIVE UNIQUE (ARCHIVE_DAY, POINT_ID),
  CONSTRAINT FK_TS_DAY_ARCHIVE_TRANS FOREIGN KEY (TRANSFORMER_ID) REFERENCES BOX_TRANSFORMER (ID),
  CONSTRAINT FK_TS_DAY_ARCHIVE_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES POWER_CIRCUIT (ID),
  CONSTRAINT FK_TS_DAY_ARCHIVE_POINT FOREIGN KEY (POINT_ID) REFERENCES MEASURE_POINT (ID),
  CONSTRAINT CK_TS_DAY_ARCHIVE_QUALITY CHECK (MAX_QUALITY_FLAG IN (0, 1, 2))
);

CREATE SEQUENCE SEQ_DB_RUNTIME_LOG START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE SEQ_TS_RAW_DATA_DAY_ARCHIVE START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE INDEX IDX_DB_RUNTIME_LOG_CREATED ON DB_RUNTIME_LOG (CREATED_AT);
CREATE INDEX IDX_DB_RUNTIME_LOG_LEVEL_CREATED ON DB_RUNTIME_LOG (LEVEL_CODE, CREATED_AT);
CREATE INDEX IDX_TS_DAY_ARCHIVE_POINT_DAY ON TS_RAW_DATA_DAY_ARCHIVE (POINT_ID, ARCHIVE_DAY);
CREATE INDEX IDX_TS_DAY_ARCHIVE_TRANS_DAY ON TS_RAW_DATA_DAY_ARCHIVE (TRANSFORMER_ID, ARCHIVE_DAY);

INSERT INTO SIM_CONTROL (
  ID,
  RUNNING,
  ANOMALY_ENABLED,
  STARTED_AT,
  LAST_WRITE_AT,
  WRITE_COUNT,
  ALARM_COUNT,
  TASK_COUNT,
  NORMAL_INTERVAL_MS,
  ANOMALY_INTERVAL_MS,
  UPDATED_AT
)
VALUES (
  1,
  0,
  0,
  NULL,
  NULL,
  0,
  0,
  0,
  1000,
  100,
  LOCALTIMESTAMP
);

CREATE OR REPLACE PACKAGE PKG_PSM_LOG AS
  PROCEDURE WRITE_LOG(
      P_LEVEL_CODE IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2,
      P_MESSAGE    IN VARCHAR2,
      P_CONTEXT    IN VARCHAR2 DEFAULT NULL
  );
END PKG_PSM_LOG;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_LOG AS
  PROCEDURE WRITE_LOG(
      P_LEVEL_CODE IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2,
      P_MESSAGE    IN VARCHAR2,
      P_CONTEXT    IN VARCHAR2 DEFAULT NULL
  ) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    INSERT INTO DB_RUNTIME_LOG (
      ID,
      LEVEL_CODE,
      EVENT_TYPE,
      MESSAGE,
      CONTEXT,
      CREATED_AT
    )
    VALUES (
      SEQ_DB_RUNTIME_LOG.NEXTVAL,
      UPPER(NVL(P_LEVEL_CODE, 'INFO')),
      SUBSTR(NVL(P_EVENT_TYPE, 'GENERAL'), 1, 50),
      SUBSTR(NVL(P_MESSAGE, 'N/A'), 1, 500),
      SUBSTR(P_CONTEXT, 1, 1000),
      LOCALTIMESTAMP
    );
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
  END WRITE_LOG;
END PKG_PSM_LOG;
/

CREATE OR REPLACE PACKAGE PKG_PSM_SIM AS
  PROCEDURE START_RUN;
  PROCEDURE STOP_RUN;
  PROCEDURE SET_ANOMALY(P_ENABLED IN NUMBER);
  PROCEDURE TICK;
  PROCEDURE GET_STATUS(P_CURSOR OUT SYS_REFCURSOR);
END PKG_PSM_SIM;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_SIM AS
  C_NORMAL_INTERVAL_MS CONSTANT NUMBER := 1000;
  C_ANOMALY_INTERVAL_MS CONSTANT NUMBER := 100;

  FUNCTION HAS_MEASURE_POINT_SOFT_DELETE RETURN NUMBER IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1)
    INTO V_COUNT
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'MEASURE_POINT'
      AND COLUMN_NAME = 'IS_DELETED';

    RETURN CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
  END HAS_MEASURE_POINT_SOFT_DELETE;

  PROCEDURE ENSURE_CONTROL_ROW IS
    V_COUNT NUMBER;
  BEGIN
    SELECT COUNT(1) INTO V_COUNT FROM SIM_CONTROL WHERE ID = 1;
    IF V_COUNT = 0 THEN
      INSERT INTO SIM_CONTROL (
        ID,
        RUNNING,
        ANOMALY_ENABLED,
        WRITE_COUNT,
        ALARM_COUNT,
        TASK_COUNT,
        NORMAL_INTERVAL_MS,
        ANOMALY_INTERVAL_MS,
        UPDATED_AT
      )
      VALUES (
        1,
        0,
        0,
        0,
        0,
        0,
        C_NORMAL_INTERVAL_MS,
        C_ANOMALY_INTERVAL_MS,
        LOCALTIMESTAMP
      );
    END IF;
  END ENSURE_CONTROL_ROW;

  FUNCTION NEXT_VALUE(
      P_MEASURE_TYPE IN VARCHAR2,
      P_UNIT         IN VARCHAR2,
      P_MAX_LIMIT    IN NUMBER,
      P_ANOMALY      IN NUMBER,
      P_WRITE_COUNT  IN NUMBER
  ) RETURN NUMBER IS
    V_TYPE  VARCHAR2(50) := UPPER(NVL(P_MEASURE_TYPE, ''));
    V_UNIT  VARCHAR2(20) := UPPER(NVL(P_UNIT, ''));
    V_BASE  NUMBER := 0;
    V_DRIFT NUMBER := 0;
  BEGIN
    CASE V_TYPE
      WHEN 'VOLTAGE' THEN
        IF V_UNIT = 'V' THEN
          V_BASE := CASE WHEN P_ANOMALY = 1 THEN 445 ELSE 400 END;
        ELSE
          V_BASE := CASE WHEN P_ANOMALY = 1 THEN 11.2 ELSE 10.1 END;
        END IF;
      WHEN 'CURRENT' THEN
        V_BASE := NVL(P_MAX_LIMIT, 100) * CASE WHEN P_ANOMALY = 1 THEN 1.08 ELSE 0.62 END;
      WHEN 'POWER_FACTOR' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 0.7800 ELSE 0.9300 END;
      WHEN 'ENERGY' THEN
        V_BASE := 12000 + (NVL(P_WRITE_COUNT, 0) * 0.0200);
      WHEN 'FREQUENCY' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 49.2000 ELSE 50.0200 END;
      WHEN 'OIL_TEMP' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 91.0000 ELSE 63.0000 END;
      WHEN 'CABINET_TEMP' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 50.0000 ELSE 32.0000 END;
      WHEN 'CABINET_HUMIDITY' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 88.0000 ELSE 55.0000 END;
      WHEN 'SWITCH_STATUS' THEN
        V_BASE := 1;
      WHEN 'FUSE_STATUS' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 1 ELSE 0 END;
      WHEN 'SMOKE_STATUS' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 1 ELSE 0 END;
      WHEN 'DOOR_STATUS' THEN
        V_BASE := CASE WHEN P_ANOMALY = 1 THEN 1 ELSE 0 END;
      ELSE
        V_BASE := 0;
    END CASE;

    IF V_TYPE NOT IN ('SWITCH_STATUS', 'FUSE_STATUS', 'SMOKE_STATUS', 'DOOR_STATUS', 'POWER_FACTOR') THEN
      V_DRIFT := (MOD(NVL(P_WRITE_COUNT, 0), 7) - 3) * 0.0500;
    END IF;

    RETURN ROUND(V_BASE + V_DRIFT, 4);
  END NEXT_VALUE;

  FUNCTION IS_OUT_OF_RANGE(
      P_MIN_LIMIT IN NUMBER,
      P_MAX_LIMIT IN NUMBER,
      P_VALUE     IN NUMBER
  ) RETURN NUMBER IS
  BEGIN
    IF P_MIN_LIMIT IS NOT NULL AND P_VALUE < P_MIN_LIMIT THEN
      RETURN 1;
    END IF;

    IF P_MAX_LIMIT IS NOT NULL AND P_VALUE > P_MAX_LIMIT THEN
      RETURN 1;
    END IF;

    RETURN 0;
  END IS_OUT_OF_RANGE;

  FUNCTION ALARM_TYPE_FOR(
      P_MEASURE_TYPE IN VARCHAR2,
      P_MIN_LIMIT    IN NUMBER,
      P_VALUE        IN NUMBER
  ) RETURN VARCHAR2 IS
  BEGIN
    IF UPPER(NVL(P_MEASURE_TYPE, '')) = 'POWER_FACTOR'
       AND P_MIN_LIMIT IS NOT NULL
       AND P_VALUE < P_MIN_LIMIT THEN
      RETURN 'POWER_FACTOR_LOW';
    END IF;

    RETURN 'RANGE_LIMIT';
  END ALARM_TYPE_FOR;

  PROCEDURE OPEN_TASK_FOR_ALARM(P_ALARM_ID IN NUMBER) IS
  BEGIN
    INSERT INTO MAINT_TASK (
      TASK_ID,
      ALARM_ID,
      STATUS,
      ASSIGNEE,
      FEEDBACK,
      CREATED_AT,
      UPDATED_AT,
      FINISHED_AT
    )
    VALUES (
      SEQ_MAINT_TASK.NEXTVAL,
      P_ALARM_ID,
      0,
      'engineer01',
      NULL,
      LOCALTIMESTAMP,
      NULL,
      NULL
    );
  END OPEN_TASK_FOR_ALARM;

  PROCEDURE HANDLE_POINT(
      P_TRANSFORMER_ID IN NUMBER,
      P_CIRCUIT_ID     IN NUMBER,
      P_POINT_ID       IN NUMBER,
      P_POINT_CODE     IN VARCHAR2,
      P_POINT_NAME     IN VARCHAR2,
      P_MEASURE_TYPE   IN VARCHAR2,
      P_UNIT           IN VARCHAR2,
      P_MIN_LIMIT      IN NUMBER,
      P_MAX_LIMIT      IN NUMBER,
      P_SAMPLE_TIME    IN TIMESTAMP,
      P_ANOMALY        IN NUMBER,
      P_WRITE_COUNT    IN NUMBER,
      P_ALARM_COUNT    IN OUT NUMBER,
      P_TASK_COUNT     IN OUT NUMBER
  ) IS
    V_VALUE           NUMBER;
    V_QUALITY_FLAG    NUMBER;
    V_ALARM_ID        NUMBER;
    V_ACTIVE_ALARM_ID NUMBER;
    V_ALARM_TYPE      VARCHAR2(50);
  BEGIN
    V_VALUE := NEXT_VALUE(P_MEASURE_TYPE, P_UNIT, P_MAX_LIMIT, P_ANOMALY, P_WRITE_COUNT);
    V_QUALITY_FLAG := IS_OUT_OF_RANGE(P_MIN_LIMIT, P_MAX_LIMIT, V_VALUE);
    V_ALARM_TYPE := ALARM_TYPE_FOR(P_MEASURE_TYPE, P_MIN_LIMIT, V_VALUE);

    INSERT INTO TS_RAW_DATA (
      ID,
      TRANSFORMER_ID,
      CIRCUIT_ID,
      POINT_ID,
      SAMPLE_TIME,
      VAL,
      QUALITY_FLAG,
      CREATED_AT
    )
    VALUES (
      SEQ_TS_RAW_DATA.NEXTVAL,
      P_TRANSFORMER_ID,
      P_CIRCUIT_ID,
      P_POINT_ID,
      P_SAMPLE_TIME,
      V_VALUE,
      V_QUALITY_FLAG,
      LOCALTIMESTAMP
    );

    BEGIN
      SELECT ID
      INTO V_ACTIVE_ALARM_ID
      FROM (
        SELECT ID
        FROM ALARM_LOG
        WHERE POINT_ID = P_POINT_ID
          AND STATUS = 0
        ORDER BY ID DESC
      )
      WHERE ROWNUM = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_ACTIVE_ALARM_ID := NULL;
    END;

    IF V_QUALITY_FLAG = 1 THEN
      IF V_ACTIVE_ALARM_ID IS NULL THEN
        V_ALARM_ID := SEQ_ALARM_LOG.NEXTVAL;
        INSERT INTO ALARM_LOG (
          ID,
          TRANSFORMER_ID,
          CIRCUIT_ID,
          POINT_ID,
          ALARM_TYPE,
          ALARM_LEVEL,
          START_TIME,
          END_TIME,
          START_VAL,
          END_VAL,
          STATUS,
          CREATED_AT
        )
        VALUES (
          V_ALARM_ID,
          P_TRANSFORMER_ID,
          P_CIRCUIT_ID,
          P_POINT_ID,
          V_ALARM_TYPE,
          'SERIOUS',
          P_SAMPLE_TIME,
          NULL,
          V_VALUE,
          V_VALUE,
          0,
          LOCALTIMESTAMP
        );

        OPEN_TASK_FOR_ALARM(V_ALARM_ID);
        P_ALARM_COUNT := P_ALARM_COUNT + 1;
        P_TASK_COUNT := P_TASK_COUNT + 1;
        PKG_PSM_LOG.WRITE_LOG(
          'WARN',
          'ALARM_OPEN',
          'Opened active alarm for point ' || P_POINT_CODE,
          'pointId=' || P_POINT_ID || ' pointName=' || P_POINT_NAME || ' value=' || TO_CHAR(V_VALUE)
        );
        PKG_PSM_LOG.WRITE_LOG(
          'INFO',
          'TASK_CREATE',
          'Created maintenance task for point ' || P_POINT_CODE,
          'pointId=' || P_POINT_ID || ' alarmId=' || V_ALARM_ID
        );
      ELSE
        UPDATE ALARM_LOG
        SET END_VAL = V_VALUE
        WHERE ID = V_ACTIVE_ALARM_ID;
      END IF;
    ELSIF V_ACTIVE_ALARM_ID IS NOT NULL THEN
      UPDATE ALARM_LOG
      SET
        STATUS = 1,
        END_TIME = P_SAMPLE_TIME,
        END_VAL = V_VALUE
      WHERE ID = V_ACTIVE_ALARM_ID;

      PKG_PSM_LOG.WRITE_LOG(
        'INFO',
        'ALARM_CLOSE',
        'Closed active alarm for point ' || P_POINT_CODE,
        'pointId=' || P_POINT_ID || ' pointName=' || P_POINT_NAME || ' value=' || TO_CHAR(V_VALUE)
      );
    END IF;
  END HANDLE_POINT;

  PROCEDURE START_RUN IS
  BEGIN
    ENSURE_CONTROL_ROW;
    UPDATE SIM_CONTROL
    SET
      RUNNING = 1,
      ANOMALY_ENABLED = 0,
      STARTED_AT = LOCALTIMESTAMP,
      LAST_WRITE_AT = NULL,
      WRITE_COUNT = 0,
      ALARM_COUNT = 0,
      TASK_COUNT = 0,
      NORMAL_INTERVAL_MS = C_NORMAL_INTERVAL_MS,
      ANOMALY_INTERVAL_MS = C_ANOMALY_INTERVAL_MS,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;
    COMMIT;
    PKG_PSM_LOG.WRITE_LOG('INFO', 'SIM_START', 'Simulation started', 'normalIntervalMs=1000 anomalyIntervalMs=100');
  END START_RUN;

  PROCEDURE STOP_RUN IS
  BEGIN
    ENSURE_CONTROL_ROW;
    UPDATE SIM_CONTROL
    SET
      RUNNING = 0,
      ANOMALY_ENABLED = 0,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;
    COMMIT;
    PKG_PSM_LOG.WRITE_LOG('INFO', 'SIM_STOP', 'Simulation stopped', NULL);
  END STOP_RUN;

  PROCEDURE SET_ANOMALY(P_ENABLED IN NUMBER) IS
  BEGIN
    ENSURE_CONTROL_ROW;
    UPDATE SIM_CONTROL
    SET
      ANOMALY_ENABLED = CASE WHEN NVL(P_ENABLED, 0) = 0 THEN 0 ELSE 1 END,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;
    COMMIT;
    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'SIM_MODE',
      CASE WHEN NVL(P_ENABLED, 0) = 0 THEN 'Simulation switched to normal mode' ELSE 'Simulation switched to anomaly mode' END,
      CASE WHEN NVL(P_ENABLED, 0) = 0 THEN 'currentIntervalMs=1000' ELSE 'currentIntervalMs=100' END
    );
  END SET_ANOMALY;

  PROCEDURE TICK IS
    V_RUNNING             NUMBER;
    V_ANOMALY_ENABLED     NUMBER;
    V_LAST_WRITE_AT       TIMESTAMP;
    V_WRITE_COUNT         NUMBER;
    V_ALARM_COUNT         NUMBER;
    V_TASK_COUNT          NUMBER;
    V_NORMAL_INTERVAL_MS  NUMBER;
    V_ANOMALY_INTERVAL_MS NUMBER;
    V_CURRENT_INTERVAL_MS NUMBER;
    V_SAMPLE_TIME         TIMESTAMP := LOCALTIMESTAMP;
    V_HAS_SOFT_DELETE     NUMBER;
    V_POINT_CURSOR        SYS_REFCURSOR;
    V_POINT_ID            NUMBER;
    V_TRANSFORMER_ID      NUMBER;
    V_CIRCUIT_ID          NUMBER;
    V_POINT_CODE          VARCHAR2(64);
    V_POINT_NAME          VARCHAR2(100);
    V_MEASURE_TYPE        VARCHAR2(50);
    V_UNIT                VARCHAR2(20);
    V_MIN_LIMIT           NUMBER;
    V_MAX_LIMIT           NUMBER;
  BEGIN
    ENSURE_CONTROL_ROW;

    SELECT
      RUNNING,
      ANOMALY_ENABLED,
      LAST_WRITE_AT,
      WRITE_COUNT,
      ALARM_COUNT,
      TASK_COUNT,
      NORMAL_INTERVAL_MS,
      ANOMALY_INTERVAL_MS
    INTO
      V_RUNNING,
      V_ANOMALY_ENABLED,
      V_LAST_WRITE_AT,
      V_WRITE_COUNT,
      V_ALARM_COUNT,
      V_TASK_COUNT,
      V_NORMAL_INTERVAL_MS,
      V_ANOMALY_INTERVAL_MS
    FROM SIM_CONTROL
    WHERE ID = 1
    FOR UPDATE;

    IF V_RUNNING = 0 THEN
      COMMIT;
      RETURN;
    END IF;

    V_CURRENT_INTERVAL_MS := CASE WHEN V_ANOMALY_ENABLED = 1 THEN V_ANOMALY_INTERVAL_MS ELSE V_NORMAL_INTERVAL_MS END;

    IF V_LAST_WRITE_AT IS NOT NULL
       AND V_SAMPLE_TIME < (V_LAST_WRITE_AT + NUMTODSINTERVAL(V_CURRENT_INTERVAL_MS / 1000, 'SECOND')) THEN
      COMMIT;
      RETURN;
    END IF;

    V_HAS_SOFT_DELETE := HAS_MEASURE_POINT_SOFT_DELETE;

    IF V_HAS_SOFT_DELETE = 1 THEN
      OPEN V_POINT_CURSOR FOR
        'SELECT
           ID,
           TRANSFORMER_ID,
           CIRCUIT_ID,
           POINT_CODE,
           POINT_NAME,
           MEASURE_TYPE,
           UNIT,
           MIN_LIMIT,
           MAX_LIMIT
         FROM MEASURE_POINT
         WHERE STATUS = 0
           AND NVL(IS_DELETED, 0) = 0
         ORDER BY TRANSFORMER_ID, CIRCUIT_ID NULLS LAST, ID';
    ELSE
      OPEN V_POINT_CURSOR FOR
        'SELECT
           ID,
           TRANSFORMER_ID,
           CIRCUIT_ID,
           POINT_CODE,
           POINT_NAME,
           MEASURE_TYPE,
           UNIT,
           MIN_LIMIT,
           MAX_LIMIT
         FROM MEASURE_POINT
         WHERE STATUS = 0
         ORDER BY TRANSFORMER_ID, CIRCUIT_ID NULLS LAST, ID';
    END IF;

    LOOP
      FETCH V_POINT_CURSOR INTO
        V_POINT_ID,
        V_TRANSFORMER_ID,
        V_CIRCUIT_ID,
        V_POINT_CODE,
        V_POINT_NAME,
        V_MEASURE_TYPE,
        V_UNIT,
        V_MIN_LIMIT,
        V_MAX_LIMIT;
      EXIT WHEN V_POINT_CURSOR%NOTFOUND;

      V_WRITE_COUNT := V_WRITE_COUNT + 1;
      HANDLE_POINT(
        V_TRANSFORMER_ID,
        V_CIRCUIT_ID,
        V_POINT_ID,
        V_POINT_CODE,
        V_POINT_NAME,
        V_MEASURE_TYPE,
        V_UNIT,
        V_MIN_LIMIT,
        V_MAX_LIMIT,
        V_SAMPLE_TIME,
        V_ANOMALY_ENABLED,
        V_WRITE_COUNT,
        V_ALARM_COUNT,
        V_TASK_COUNT
      );
    END LOOP;

    CLOSE V_POINT_CURSOR;

    UPDATE SIM_CONTROL
    SET
      LAST_WRITE_AT = V_SAMPLE_TIME,
      WRITE_COUNT = V_WRITE_COUNT,
      ALARM_COUNT = V_ALARM_COUNT,
      TASK_COUNT = V_TASK_COUNT,
      UPDATED_AT = LOCALTIMESTAMP
    WHERE ID = 1;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      IF V_POINT_CURSOR%ISOPEN THEN
        CLOSE V_POINT_CURSOR;
      END IF;
      ROLLBACK;
      PKG_PSM_LOG.WRITE_LOG('ERROR', 'SIM_TICK', SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RAISE;
  END TICK;

  PROCEDURE GET_STATUS(P_CURSOR OUT SYS_REFCURSOR) IS
  BEGIN
    ENSURE_CONTROL_ROW;
    OPEN P_CURSOR FOR
      SELECT
        RUNNING,
        ANOMALY_ENABLED,
        STARTED_AT,
        LAST_WRITE_AT,
        WRITE_COUNT,
        ALARM_COUNT,
        TASK_COUNT,
        NORMAL_INTERVAL_MS,
        ANOMALY_INTERVAL_MS,
        CASE WHEN ANOMALY_ENABLED = 1 THEN ANOMALY_INTERVAL_MS ELSE NORMAL_INTERVAL_MS END AS CURRENT_INTERVAL_MS
      FROM SIM_CONTROL
      WHERE ID = 1;
  END GET_STATUS;
END PKG_PSM_SIM;
/

CREATE OR REPLACE PACKAGE PKG_PSM_TASK AS
  PROCEDURE UPDATE_TASK(
      P_TASK_ID   IN NUMBER,
      P_STATUS    IN NUMBER,
      P_ASSIGNEE  IN VARCHAR2,
      P_FEEDBACK  IN VARCHAR2,
      P_ACTOR     IN VARCHAR2
  );
END PKG_PSM_TASK;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_TASK AS
  PROCEDURE UPDATE_TASK(
      P_TASK_ID   IN NUMBER,
      P_STATUS    IN NUMBER,
      P_ASSIGNEE  IN VARCHAR2,
      P_FEEDBACK  IN VARCHAR2,
      P_ACTOR     IN VARCHAR2
  ) IS
  BEGIN
    IF P_STATUS NOT IN (0, 1, 2) THEN
      RAISE_APPLICATION_ERROR(-20001, 'Invalid task status.');
    END IF;

    UPDATE MAINT_TASK
    SET
      STATUS = P_STATUS,
      ASSIGNEE = NULLIF(TRIM(P_ASSIGNEE), ''),
      FEEDBACK = NULLIF(TRIM(P_FEEDBACK), ''),
      UPDATED_AT = LOCALTIMESTAMP,
      FINISHED_AT = CASE
        WHEN P_STATUS = 2 THEN NVL(FINISHED_AT, LOCALTIMESTAMP)
        ELSE NULL
      END
    WHERE TASK_ID = P_TASK_ID;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'Task does not exist.');
    END IF;

    COMMIT;
    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'TASK_UPDATE',
      'Updated maintenance task ' || P_TASK_ID,
      'status=' || P_STATUS || ' actor=' || NVL(P_ACTOR, 'unknown')
    );
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PKG_PSM_LOG.WRITE_LOG('ERROR', 'TASK_UPDATE', SQLERRM, 'taskId=' || P_TASK_ID);
      RAISE;
  END UPDATE_TASK;
END PKG_PSM_TASK;
/

CREATE OR REPLACE PACKAGE PKG_PSM_ARCHIVE AS
  PROCEDURE ARCHIVE_EXPIRED_RAW;
END PKG_PSM_ARCHIVE;
/

CREATE OR REPLACE PACKAGE BODY PKG_PSM_ARCHIVE AS
  PROCEDURE ARCHIVE_EXPIRED_RAW IS
    V_CUTOFF_DAY     DATE := TRUNC(CURRENT_DATE) - 30;
    V_MERGED_ROWS    NUMBER := 0;
    V_DELETED_RAW    NUMBER := 0;
    V_DELETED_LOGS   NUMBER := 0;
  BEGIN
    PKG_PSM_LOG.WRITE_LOG('INFO', 'ARCHIVE_START', 'Started raw data archive job', 'cutoffDay=' || TO_CHAR(V_CUTOFF_DAY, 'YYYY-MM-DD'));

    MERGE INTO TS_RAW_DATA_DAY_ARCHIVE DST
    USING (
      SELECT
        TRUNC(R.SAMPLE_TIME) AS ARCHIVE_DAY,
        R.TRANSFORMER_ID,
        R.CIRCUIT_ID,
        R.POINT_ID,
        CASE
          WHEN UPPER(MP.MEASURE_TYPE) IN ('ENERGY', 'SWITCH_STATUS', 'FUSE_STATUS', 'SMOKE_STATUS', 'DOOR_STATUS')
            THEN ROUND(MAX(R.VAL), 4)
          ELSE ROUND(AVG(R.VAL), 4)
        END AS DISPLAY_VAL,
        ROUND(AVG(R.VAL), 4) AS AVG_VAL,
        ROUND(MIN(R.VAL), 4) AS MIN_VAL,
        ROUND(MAX(R.VAL), 4) AS MAX_VAL,
        COUNT(*) AS SAMPLE_COUNT,
        MAX(R.QUALITY_FLAG) AS MAX_QUALITY_FLAG
      FROM TS_RAW_DATA R
      JOIN MEASURE_POINT MP ON MP.ID = R.POINT_ID
      WHERE R.SAMPLE_TIME < V_CUTOFF_DAY
      GROUP BY
        TRUNC(R.SAMPLE_TIME),
        R.TRANSFORMER_ID,
        R.CIRCUIT_ID,
        R.POINT_ID,
        UPPER(MP.MEASURE_TYPE)
    ) SRC
    ON (
      DST.ARCHIVE_DAY = SRC.ARCHIVE_DAY
      AND DST.POINT_ID = SRC.POINT_ID
    )
    WHEN MATCHED THEN UPDATE
    SET
      DST.TRANSFORMER_ID = SRC.TRANSFORMER_ID,
      DST.CIRCUIT_ID = SRC.CIRCUIT_ID,
      DST.DISPLAY_VAL = SRC.DISPLAY_VAL,
      DST.AVG_VAL = SRC.AVG_VAL,
      DST.MIN_VAL = SRC.MIN_VAL,
      DST.MAX_VAL = SRC.MAX_VAL,
      DST.SAMPLE_COUNT = SRC.SAMPLE_COUNT,
      DST.MAX_QUALITY_FLAG = SRC.MAX_QUALITY_FLAG,
      DST.CREATED_AT = LOCALTIMESTAMP
    WHEN NOT MATCHED THEN
      INSERT (
        ID,
        ARCHIVE_DAY,
        TRANSFORMER_ID,
        CIRCUIT_ID,
        POINT_ID,
        DISPLAY_VAL,
        AVG_VAL,
        MIN_VAL,
        MAX_VAL,
        SAMPLE_COUNT,
        MAX_QUALITY_FLAG,
        CREATED_AT
      )
      VALUES (
        SEQ_TS_RAW_DATA_DAY_ARCHIVE.NEXTVAL,
        SRC.ARCHIVE_DAY,
        SRC.TRANSFORMER_ID,
        SRC.CIRCUIT_ID,
        SRC.POINT_ID,
        SRC.DISPLAY_VAL,
        SRC.AVG_VAL,
        SRC.MIN_VAL,
        SRC.MAX_VAL,
        SRC.SAMPLE_COUNT,
        SRC.MAX_QUALITY_FLAG,
        LOCALTIMESTAMP
      );
    V_MERGED_ROWS := SQL%ROWCOUNT;

    DELETE FROM TS_RAW_DATA
    WHERE SAMPLE_TIME < V_CUTOFF_DAY;
    V_DELETED_RAW := SQL%ROWCOUNT;

    DELETE FROM DB_RUNTIME_LOG
    WHERE CREATED_AT < (LOCALTIMESTAMP - NUMTODSINTERVAL(30, 'DAY'));
    V_DELETED_LOGS := SQL%ROWCOUNT;

    COMMIT;
    PKG_PSM_LOG.WRITE_LOG(
      'INFO',
      'ARCHIVE_DONE',
      'Finished raw data archive job',
      'mergedRows=' || V_MERGED_ROWS || ' deletedRaw=' || V_DELETED_RAW || ' deletedLogs=' || V_DELETED_LOGS
    );
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      PKG_PSM_LOG.WRITE_LOG('ERROR', 'ARCHIVE_FAIL', SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RAISE;
  END ARCHIVE_EXPIRED_RAW;
END PKG_PSM_ARCHIVE;
/

BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'JOB_PSM_ARCHIVE_RAW',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN PKG_PSM_ARCHIVE.ARCHIVE_EXPIRED_RAW; END;',
    START_DATE      => CURRENT_TIMESTAMP,
    REPEAT_INTERVAL => 'FREQ=DAILY;BYHOUR=0;BYMINUTE=5;BYSECOND=0',
    ENABLED         => TRUE,
    COMMENTS        => 'Archive raw samples older than 30 days and trim DB runtime logs.'
  );
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-27486, -1031) THEN
      PKG_PSM_LOG.WRITE_LOG(
        'WARN',
        'ARCHIVE_JOB_SKIP',
        'Skipped creating JOB_PSM_ARCHIVE_RAW because CREATE JOB is not granted.',
        SUBSTR(SQLERRM, 1, 1000)
      );
    ELSE
      RAISE_APPLICATION_ERROR(
        -20030,
        'Failed to create JOB_PSM_ARCHIVE_RAW. Root cause: ' || SUBSTR(SQLERRM, 1, 280)
      );
    END IF;
END;
/

COMMIT;
