/*
  PSM-Smart Oracle 21c localized seed data patch.

  Converts display-oriented seed values to Chinese while keeping technical codes unchanged.
*/

UPDATE SYS_USER SET DISPLAY_NAME = '系统管理员' WHERE USERNAME = 'admin';
UPDATE SYS_USER SET DISPLAY_NAME = '运行值班员' WHERE USERNAME = 'operator';
UPDATE SYS_USER SET DISPLAY_NAME = '检修工程师一号' WHERE USERNAME = 'engineer01';
UPDATE SYS_USER SET DISPLAY_NAME = '运维主管' WHERE USERNAME = 'manager';

UPDATE BOX_TRANSFORMER
SET NAME = '东园区一号箱变',
    MANUFACTURER = '华东电气设备有限公司',
    LOCATION = '东园区 A 区配电房'
WHERE TRANSFORMER_CODE = 'BOX-TR-001';

UPDATE POWER_CIRCUIT SET NAME = '10kV 进线回路' WHERE CIRCUIT_CODE = 'IN01';
UPDATE POWER_CIRCUIT SET NAME = '0.4kV 出线一回路' WHERE CIRCUIT_CODE = 'OUT01';
UPDATE POWER_CIRCUIT SET NAME = '0.4kV 出线二回路' WHERE CIRCUIT_CODE = 'OUT02';

UPDATE MEASURE_POINT SET POINT_NAME = '进线 AB 电压' WHERE POINT_CODE = 'IN01_VOLTAGE_AB';
UPDATE MEASURE_POINT SET POINT_NAME = '进线 A 相电流' WHERE POINT_CODE = 'IN01_CURRENT_A';
UPDATE MEASURE_POINT SET POINT_NAME = '进线功率因数' WHERE POINT_CODE = 'IN01_POWER_FACTOR';
UPDATE MEASURE_POINT SET POINT_NAME = '进线电能' WHERE POINT_CODE = 'IN01_ENERGY';
UPDATE MEASURE_POINT SET POINT_NAME = '进线频率' WHERE POINT_CODE = 'IN01_FREQUENCY';
UPDATE MEASURE_POINT SET POINT_NAME = '出线一电压' WHERE POINT_CODE = 'OUT01_VOLTAGE';
UPDATE MEASURE_POINT SET POINT_NAME = '出线一电流' WHERE POINT_CODE = 'OUT01_CURRENT';
UPDATE MEASURE_POINT SET POINT_NAME = '出线一功率因数' WHERE POINT_CODE = 'OUT01_POWER_FACTOR';
UPDATE MEASURE_POINT SET POINT_NAME = '出线一电能' WHERE POINT_CODE = 'OUT01_ENERGY';
UPDATE MEASURE_POINT SET POINT_NAME = '出线二电压' WHERE POINT_CODE = 'OUT02_VOLTAGE';
UPDATE MEASURE_POINT SET POINT_NAME = '出线二电流' WHERE POINT_CODE = 'OUT02_CURRENT';
UPDATE MEASURE_POINT SET POINT_NAME = '出线二功率因数' WHERE POINT_CODE = 'OUT02_POWER_FACTOR';
UPDATE MEASURE_POINT SET POINT_NAME = '出线二电能' WHERE POINT_CODE = 'OUT02_ENERGY';
UPDATE MEASURE_POINT SET POINT_NAME = '箱变油温' WHERE POINT_CODE = 'BOX_OIL_TEMP';
UPDATE MEASURE_POINT SET POINT_NAME = '负荷开关状态' WHERE POINT_CODE = 'BOX_SWITCH_STATUS';
UPDATE MEASURE_POINT SET POINT_NAME = '熔断器状态' WHERE POINT_CODE = 'BOX_FUSE_STATUS';
UPDATE MEASURE_POINT SET POINT_NAME = '柜内温度' WHERE POINT_CODE = 'CABINET_TEMP';
UPDATE MEASURE_POINT SET POINT_NAME = '柜内湿度' WHERE POINT_CODE = 'CABINET_HUMIDITY';
UPDATE MEASURE_POINT SET POINT_NAME = '烟雾传感器状态' WHERE POINT_CODE = 'CABINET_SMOKE_STATUS';
UPDATE MEASURE_POINT SET POINT_NAME = '柜门状态' WHERE POINT_CODE = 'CABINET_DOOR_STATUS';

UPDATE CABINET_DOOR_LOG
SET NOTE = '例行开柜巡检开始。'
WHERE NOTE = 'Routine cabinet inspection started.';

UPDATE CABINET_DOOR_LOG
SET NOTE = '例行开柜巡检结束。'
WHERE NOTE = 'Routine cabinet inspection finished.';

COMMIT;
